### PR TITLE
Protocol: prevent allocations when insert known ops

### PR DESCRIPTION
**Pull request by gterzian**
Fix https://github.com/massalabs/massa/issues/2553

### CODE REVIEW

**Review by damip — DISMISSED** [review]

**Comment by damip** [comment]
Only a couple downsides:

* I don't know why the initial approach created such a problem (?)
* maybe we should do a preallocation (with_capacity) for both the hashmap and the deque to avoid allows when resizing
* we should reduce the known_ops_size value in the config to something like 2048
* the new algorith does 2 hashmap lookups instead of 1 ("contains" then "remove")

**Comment by damip** [comment]
Here is a better option I thinnk: https://github.com/massalabs/massa/pull/2558

**Comment by gterzian** [comment]
@damip 

> I don't know why the initial approach created such a problem

The initial problem was that when having reached the limit, we would first do an `insert`, and then a `remove`. Since the `insert` happens when the set is already at full capacity, it will re-allocate, and I think it will basically double it's capacity. 

> we should reduce the known_ops_size value in the config to something like 2048

Why? Also, in that case it still makes sense to avoid doubling the capacity just to insert one additional element.

> the new algorithm does 2 hashmap lookups instead of 1 ("contains" then "remove")

Yes, and the current problem is memory usage, not cpu. 

> Here is a better option I thinnk: https://github.com/massalabs/massa/pull/2558

It does the trick, although I think it is too convoluted(why add 1 to a config? That would surprise anyone looking at the code), and that complication is not worth saving one instruction(which may not be in fact a performance problem at all).

**Comment by damip** [comment]
> @damip
> 
> > I don't know why the initial approach created such a problem
> 
> The initial problem was that when having reached the limit, we would first do an `insert`, and then a `remove`. Since the `insert` happens when the set is already at full capacity, it will re-allocate, and I think it will basically double it's capacity.
> 
> > we should reduce the known_ops_size value in the config to something like 2048
> 
> Why? Also, in that case it still makes sense to avoid doubling the capacity just to insert one additional element.
> 
> > the new algorithm does 2 hashmap lookups instead of 1 ("contains" then "remove")
> 
> Yes, and although the current problem is memory usage, not cpu, it is still better to avoid. This can be done as in the other PR.
> 
> > Here is a better option I thinnk: #2558
> 
> If the review at [#2558 (review)](https://github.com/massalabs/massa/pull/2558#pullrequestreview-949532415) is addressed, then indeed it is better (since it removes the additional `contains` check).
> 
> It would have been better to progress via a review here.

I replied to the comments. Yeah sorry we had to rush this one through because of the time constraints. We'll be back to a normal way of working after the hackathon

**Pull request closed without merging**
