### PR TITLE
Fix spelling and improve CI to check it.

### PR DESCRIPTION
**Pull request by AurelienFT**

### CODE REVIEW

**Comment by AureliaDolo** [comment]
I'm not sure about the timing of this issue as there are some quite huge ones in progress. I would rather fis that as you go, when you encounter some typos on code you edit.

**Comment by AurelienFT** [comment]
> 

Since it's just on the comment it will not cause major merge conflict.

**Comment by AureliaDolo** [comment]
> > 
> 
> Since it's just on the comment it will not cause major merge conflict.

A lot of stuff is moving around so it may have some unexpected behavior. I would rather do that when the shared storage and operation batch feature are merged. 

I won't block this PR, but I won't approve it either. :crab:

**Comment by AurelienFT** [comment]
> > > 
> > 
> > 
> > Since it's just on the comment it will not cause major merge conflict.
> 
> A lot of stuff is moving around so it may have some unexpected behavior. I would rather do that when the shared storage and operation batch feature are merged.
> 
> I won't block this PR, but I won't approve it either. 🦀

I'm ok with merging it after the big features I wasn't ok on doing it along the way.

**Review by damip — DISMISSED** [review]
LGTM. Let's just make sure we don't create too many conflicts and/or lose some of the corrections made here

**Comment by damip** [comment]
After this PR, it could be nice to have a spell checker in the CI

**Comment by AurelienFT** [comment]
> After this PR, it could be nice to have a spell checker in the CI to avoid having to do it again

I'll add it in this PR

**Comment by AureliaDolo** [comment]
I think you can either resurrect this pr or start again from main

**Comment by AurelienFT** [comment]
Even if this PR have a lot of changes it's just spelling in comments. I think we can merge it fast so that it don't block the rest.

**Comment by gterzian** [comment]
Ok for me, will approave after the conflict has been fixed. @AurelienFT

**Comment by AurelienFT** [comment]
> Ok for me, will approve after the conflict has been fixed. @AurelienFT

Done :)

**Review by gterzian — APPROVED** [review]

**Comment by gterzian** [comment]
bors merge

**Comment by AurelienFT** [comment]
Ok it recompiles the package `cargo-spellcheck` each day because I think we are on a newer version of Rust and so the cache don't work. Either we assume each day a pipeline will take 10 min more or we fix a version on CI ? @yvan-sraka

**Review by damip — APPROVED** [review]

**Pull request merged**
