### PR TITLE
Use ubuntu 18 for CD

### PR DESCRIPTION
**Pull request by qdrn**

### CODE REVIEW

**Comment by yvan-sraka** [comment]
What … who want an Ubuntu version released in 2018 for CD ... and why ?!

**Comment by yvan-sraka** [comment]
Last LTS is **20.04.3** https://wiki.ubuntu.com/Releases

**Comment by damip** [comment]
Since the CD was updated, we had trouble with a whole bunch of people running CENTOS and other flavors with older GLIBC versions, especially on VPS. Not everyone keeps their GLIBC up-to-date :)

**Review by damip — APPROVED** [review]

**Comment by damip** [comment]
bors merge

**Comment by yvan-sraka** [comment]
> Since the CD was updated, we had trouble with a whole bunch of people running CENTOS and other flavors with older GLIBC versions, especially on VPS. Not everyone keeps their GLIBC up-to-date :)

Why not having an up-to-date Linux with just an old GLIBC?

**Comment by damip** [comment]
> > Since the CD was updated, we had trouble with a whole bunch of people running CENTOS and other flavors with older GLIBC versions, especially on VPS. Not everyone keeps their GLIBC up-to-date :)
> 
> Why not having an up-to-date Linux with just an old GLIBC?

that's not easy to do, is it ? because most of the OS depends on it

**Comment by damip** [comment]
https://github.com/massalabs/massa/issues/2168

**Pull request merged**
