### PR TITLE
Add all contributors

### LINKED ISSUE #1069: Add initial contributors
In GitLab by @AureliaDolo

### PR DESCRIPTION
**Pull request by AurelienFT**
Fix #1069

### CODE REVIEW

**Review by Eitu33 — DISMISSED** [review]

**Comment by Eitu33** [comment]
Probably should do this in runtime too

**Review by damip — DISMISSED** [review]

**Comment by damip** [comment]
A contributor that helped us initialize the project (back on gitlab) is missing:  https://github.com/flipchan

**Review by damip — APPROVED** [review]

**Comment by AurelienFT** [comment]
bors merge

**Comment by AurelienFT** [comment]
bors merge

**Comment by AurelienFT** [comment]
no space left.... these runners :'(

**Pull request merged**
