### PR TITLE
Add submodule documentation & port CILight

### PR DESCRIPTION
**Pull request by adrien-zinger**
Add a missing link of documentation submodule in this branch

### CODE REVIEW

**Comment by yvan-sraka** [comment]
Whats's the purpose of `CILight`? couldn't it be just a job `minimal` in current `CI.yml`?

**Comment by yvan-sraka** [comment]
Whats's the purpose of `CILight`? couldn't it be just a job `minimal` in current `CI.yml`?

**Comment by adrien-zinger** [comment]
> Whats's the purpose of `CILight`? couldn't it be just a job `minimal` in current `CI.yml`?

CILight will do the job only if you target another branch than main, target or staging. It's useful when you make a pr on a pr.

I'm not sure if we can do all of that in just the CI.yml.

**Comment by yvan-sraka** [comment]
> `CILight` will do the job only if you target another branch than `main`, `target` or `staging`. It's useful when you make a PR on a PR.

Neat 🔥

> I'm not sure if we can do all of that in just the `CI.yml`?

We can do everything in `CI.yml` and maybe it's also a good occasion to comment/reorganise it, maybe split it in 3 files:

- clippy check for PRs (quick CI)
- bors-related stuffs (full CI)
- doc and coverage reports (post-merge CI)

**Review by damip — APPROVED** [review]

**Pull request merged**
