### PR TITLE
New cryptocraphic crate for ed25519.

### PR DESCRIPTION
**Pull request by AurelienFT**

### CODE REVIEW

**Review by damip — APPROVED** [review]
perfect !

**Comment by damip** [comment]
bors merge

**Review by damip — APPROVED** [review]

**Comment by AurelienFT** [comment]
Rand version downgrade cause of this : https://github.com/dalek-cryptography/ed25519-dalek/pull/184

**Comment by damip** [comment]
bors merge

**Review by damip — APPROVED** [review]

**Comment by damip** [comment]
bors merge

**Pull request merged**
