### PR TITLE
Do not create initial cycle when the node did not bootstrap

### PR DESCRIPTION
**Pull request by Eitu33**

### CODE REVIEW

**Comment by Eitu33** [comment]
@damip @AurelienFT behaviour has been tested

**Comment by damip** [comment]
I think it's "sequential", not "consequential" :)

**Comment by damip** [comment]
Out of curiosity: why remove it AFTER bootstrap, and not clear beforehand if we know that we will be bootstrapping ? I feel like it would more logical and much less error prone than keeping this artifact for so long

**Comment by Eitu33** [comment]
The initial cycle is now not created if the bootstrap happened, rather than creating it all the time and deleting it afterward.

Putting this in draft for now as the bootstrap test if failing with the new behaviour.

**Comment by Eitu33** [comment]
Done.

**Review by AurelienFT — APPROVED** [review]

**Pull request merged**
