### PR TITLE
refactor: sort list of stakers based on the number of rolls

### LINKED ISSUE #2633: Sort list of stakers based on the number of rolls
When getting stakers using get_stakers api, the list of stakers obtained is not sorted.
Sorting the list of stakers based on the number of rolls in descending order at the server side will be very useful.
This will reduce the computation time and resource at the client side, particularly for mobile devices with limited computation resources.

### PR DESCRIPTION
**Pull request by aoudiamoncef**
resolves #2633

### CODE REVIEW

**Comment by AurelienFT** [comment]
Thanks for your contribution ❤️  Can you fix the CI please @aoudiamoncef ?

**Comment by aoudiamoncef** [comment]
Hi @AurelienFT 

With `BtreeMap` we will have a natural order by keys which isn't our purpose. I did  lot of research to find a better way before changing return type to `Vec(Address, u64)>`.  

I got no issue with `cargo clippy` in local environment.

**Comment by AurelienFT** [comment]
> With `BtreeMap` we will have a natural order by keys which isn't our purpose(order by value desc). I did lot of research to find a better way before changing return type to `Vec(Address, u64)>`.

My bad I misread it.

**Comment by aoudiamoncef** [comment]
> I think you can change the return type of the function : get_active_stakers to a `BtreeMap` so that it's sorted and we don't have the API format.

We could do the trick by creating an `HashMap` from the sorted `Vec(Address, u64)>`, so we could keep method signature. But the question is: where we'll add this behaviors ?  get_active_stakers or get_stakers

**Comment by AurelienFT** [comment]
> We could do the trick by creating an `HashMap` from the sorted `Vec(Address, u64)>`, so we could keep method signature. But the question is: where we'll add this behaviors ? get_active_stakers or get_stakers

It's ok to change the behavior because we are in testnet. Just want @qdrn to look at it because he is the one maintaining the tools that use this API endpoint.

**Comment by aoudiamoncef** [comment]
We are f***d, we have to use `LinkedHashMap` structure to achieve what we need. It's frustrating to add an external crate. 

The Rust idiomatic way to solve this issue is to use `Vec(Address, u64)`.

**Comment by AurelienFT** [comment]
> The Rust idiomatic way to solve this issue is to use `Vec(Address, u64)`.

I'm ok with using A `Vec` now. Just need @qdrn approval and also so that he knew what he need to change on his side.

**Review by AurelienFT — APPROVED** [review]
I'm ok with it.

**Comment by qdrn** [comment]
> I'm ok with using A `Vec` now. Just need @qdrn approval and also so that he knew what he need to change on his side.

Either are fine for me. It will not change much the tooling in both cases.

**Comment by AurelienFT** [comment]
Ok then I merge it for the next testnet

**Comment by AurelienFT** [comment]
bors merge

**Pull request closed without merging**
