### PR TITLE
Include xor versioning

### PR DESCRIPTION
**Pull request by Leo-Besancon**
* [ ] document all added functions
* [ ] try in sandbox /simulation/labnet
* [ ] unit tests on the added/changed features
  * [ ] make tests compile
  * [ ] make tests pass 
* [ ] add logs allowing easy debugging in case the changes caused problems
* [ ] if the API has changed, update the API specification

### CODE REVIEW

**Comment by Leo-Besancon** [comment]
We need to test this on labnet and have the following behaviour:
- Before the MipInfo relative to the FinalStateHashKind becomes active, nodes with and without this PR should stay sync
- Afterwards, they are no longer sync
- Afterwards, the nodes with the MipInfo can execute more operations while staying sync

**Comment by Leo-Besancon** [comment]
/!\ The lsm_tree initialization will fail massa_db::new() if we already used XOR, I'll work on a quick fix for that

**Comment by damip** [comment]
See https://github.com/massalabs/massa/discussions/3852#discussioncomment-6188158 to make it secure

**Review by AurelienFT — APPROVED** [review]

**Comment by AurelienFT** [comment]
bors merge

**Comment by AurelienFT** [comment]
bors merge

**Pull request merged**
