### PR TITLE
Add tests for pool endorsements

### PR DESCRIPTION
**Pull request by AurelienFT**
`massa-pool-worker` now has 79% coverage

### CODE REVIEW

**Review by Leo-Besancon — COMMENTED** [review]
The tests you added look good to me.

In the operation_pool_tester, there seems to be a lot of TODOs, e.g.
```
/// TODO refactor old tests
```

Have you checked if these still make sence?

**Comment by AurelienFT** [comment]
@Leo-Besancon I just checked and most of them just comment things that are tested in an other way in the file and so I have removed them.

**Review by Leo-Besancon — APPROVED** [review]
Great!

**Review by Eitu33 — APPROVED** [review]

**Comment by AurelienFT** [comment]
bors merge

**Pull request merged**
