### PR TITLE
Fix bootstrap server error on retry

### PR DESCRIPTION
**Pull request by Eitu33**

### CODE REVIEW

**Comment by AurelienFT** [comment]
Fix #3572

**Review by AurelienFT — COMMENTED** [review]
I think 300 is too magical we could put the number of block we keep in consensus. I think we only keep 10 periods (variable `force_keep_final_periods` in config.toml) so 10*32 = 320 could be great with a comment explaining this

**Comment by Eitu33** [comment]
I disagree because the `force_keep_final_periods` is in the dynamic config and that would make the payload limit accessible  to the user. We do not want that.

**Review by AurelienFT — APPROVED** [review]
You convinced me that there is no good solution. Let's keep it like that for now and change in the future if needed

**Pull request merged**
