### PR TITLE
Add doc-test with testing feature to CI steps

### PR DESCRIPTION
**Pull request by Ben-PH**
* [ ] document all added functions
* [ ] try in sandbox /simulation/labnet
* [ ] unit tests on the added/changed features
  * [ ] make tests compile
  * [ ] make tests pass 
* [ ] add logs allowing easy debugging in case the changes caused problems
* [ ] if the API has changed, update the API specification

### CODE REVIEW

**Comment by AurelienFT** [comment]
@Ben-PH Why did you moved it out ? Because it will not benefit from the cache from other tasks but it also not be run on the matrix with multiple OS.

**Comment by Ben-PH** [comment]
My thinking is that doctests are at a much higher level, and are platform agnostic, so I thought just the one OS is sufficient.

Losing the cache, yeah, probably not the best.

Writing good CI scripts is very much in the "something I need to develop as a skill" basket for me, so I'm playing around a bit.

Some of the things in my mind:

- Run it parallel to the unit tests might be good. Yes they are a unit test of sorts, but a different class of tests.
- No need to check across platforms: Doctests are not meant to be thorough, that's for the unit tests. Doc tests serve a dual purpose of sniff-testing for correctness at a basic level, and providing use-case-examples in the documentation. Leave the x-platform stuff to the full-test job
- didn't think that a separate doc-test would take so long to DL and compile.

On balance, the second commit doesn't seem to be a good idea, no? Lesson to be learned.

**Comment by sydhds** [comment]
Not sure to see the benefits of separating doctests from other unit tests...

**Comment by Ben-PH** [comment]
Was thinking of having them in parallel with the unit tests, but the gains are absolute minimal, the costs massive. Not worth it, I think.

**Review by sydhds — APPROVED** [review]

**Pull request merged**
