### PR TITLE
Adds binaries for Mac M1

### LINKED ISSUE #3212: Add ARM64 binaries for MacOS
**Is your feature request related to a problem? Please describe.**
For now, MacOS binaries provided in [releases](https://github.com/massalabs/massa/releases) are only available for `x86_64` processors. Most new Macs come with an `arm64` processor.

**Describe the solution you'd like**
Add `arm64` binaries for MacOS in [releases](https://github.com/massalabs/massa/releases).

**Describe alternatives you've considered**
- Let `arm64` Mac users compile binaries themselves. But that's not really user friendly and requires way more time and disk space.
- ...

**Additional context**
- Seeing how the [CD workflow](https://github.com/massalabs/massa/blob/99b5d6dab5acc31eb30da11b3ee6ff4da9cee6cc/.github/workflows/cd.yml) is made, it should be as easy as removing [MacOS `arm64`](https://github.com/massalabs/massa/blob/99b5d6dab5acc31eb30da11b3ee6ff4da9cee6cc/.github/workflows/cd.yml#L38) from the matrix [`exclude`](https://github.com/massalabs/massa/blob/99b5d6dab5acc31eb30da11b3ee6ff4da9cee6cc/.github/workflows/cd.yml#L35) and add it to the [`include`](https://github.com/massalabs/massa/blob/99b5d6dab5acc31eb30da11b3ee6ff4da9cee6cc/.github/workflows/cd.yml#L18).

### PR DESCRIPTION
**Pull request by qdrn**
Closes #3212

### CODE REVIEW

**Comment by qdrn** [comment]
Can you test the binaries generated for Mac M1 here @thomas-senechal https://github.com/qdrn/massa/releases/tag/TEST.13.0 and they work accept and merge this PR ?

**Comment by qdrn** [comment]
Can also work with @Eitu33 :)

**Review by peterjah — APPROVED** [review]
FYI, Cross does not support aarch64-apple-darwin ( at least not like this) But The build should work because it will use cargo as fallback!

**Review by AurelienFT — APPROVED** [review]
I have tested with my M1

**Comment by AurelienFT** [comment]
bors merge

**Comment by qdrn** [comment]
> FYI, Cross does not support aarch64-apple-darwin ( at least not like this) But the build should work because it will use cargo as fallback!

Thanks for the info. Maybe we can find something that is cleaner in the future.

**Pull request merged**
