### PR TITLE
Update cd.yml

### PR DESCRIPTION
**Pull request by yvan-sraka**

### CODE REVIEW

**Comment by AureliaDolo** [comment]
What is that doing in a nutshell ?

**Comment by yvan-sraka** [comment]
Rely more on the works done by https://github.com/actions-rs rather than doing our custom salsa when not strictly needed! 😉

**Review by AureliaDolo — APPROVED** [review]

**Comment by AureliaDolo** [comment]
bors merge

**Comment by yvan-sraka** [comment]
bors merge

**Comment by AureliaDolo** [comment]
bors merge

**Pull request merged**
