### PR TITLE
Allow big ledger bootstrapping

### PR DESCRIPTION
**Pull request by litchipi**
# Big ledger bootstrap

Changes in the code allowing the node to bootstrap from a big ledger.
Some changes on this PR may not be useful and has to be stripped, if you see some left please tell me.

## Tests for bootstrap using big ledger

- 111591403520 bytes  ( 104G ) :     1h 32 mins 53 secs
- 53717592215 bytes ( 52G ) :      46 mins 30 secs

It bootstraps to an average bytes per second of `19638597 bytes`, and seams to be increasing linearly.

- 200 G  ->  3h 2m 15s
- 500 G  ->  7h 35m 37s
- 800 G  ->  12h 9m 0s
- 1 To -> 15h 33m 7s
- 2 To -> 1j 7h 6m 14s
- 5 To -> 3j 5h 45m 36s
- 8 To -> 5j 4h 24m 58s
- 10 To -> 6j 11h 31m 12s

## Limits to discuss

Some configuration about the limits to set for the deserialization, timeouts, etc ... has to be discussed.
As they have been problematic during the bootstrap of 100G, they have to be adapted to the max size of the packets we can support (see https://github.com/massalabs/massa/issues/4406), but also about how long it takes to stream these packets on the network.

## Testing setup used
- Using the branch `fill_ledger` of [massa-ledger-editor](https://github.com/massalabs/massa-ledger-editor), fill an **existing** ledger to the wanted size
- Start a labnet with the necessary changes in `labnet.toml` (in addition to the existing info):
```
commit = "test_bootstrap_big"
genesis_timestamp_mins = 15

[servers.labnet0]
initial_rolls = 100
bootstrap_server = true
exec_args = [ "--keep-ledger" ]
add_script_pre_launch = [ "rsync --delete -r /path/to/edited/ledger ./storage/ledger" ]

[servers.labnet1]
initial_rolls = 0
bootstrap_server = false
add_script_pre_launch = [
  "sleep $(( 15 * 60 ))",
]
```
This ensures that `labnet1` boostraps to `labnet0`, and `labnet0` uses the edited ledger.
- Watch logs of `labnet1` till you see blocks arriving.

### CODE REVIEW

**Comment by litchipi** [comment]
@damip Look at the extrapolated times I computed, it's worrying me a bit

@Leo-Besancon Could you look at the code and tell me which security check I deleted I can safely put back ? (db valid, check desync, etc ...)
Also I removed them because we use the massa-ledger-editor, but I hope some check like this won't bother us in the case of a real big bootstrap ?

**Comment by damip** [comment]
Some ideas:

* short term: reduce block size and gas to limit TXPS and writing rates (so that the ledger grows slowly while we figure it out)
* long term: decentralize the bootstrap by making it possible to boot from multiple memebers of the community at the same time (like bittorrent) and at the end, just check the hash with a trusted bootstrap node

**Comment by Leo-Besancon** [comment]
> @damip Look at the extrapolated times I computed, it's worrying me a bit
> 
> @Leo-Besancon Could you look at the code and tell me which security check I deleted I can safely put back ? (db valid, check desync, etc ...) Also I removed them because we use the massa-ledger-editor, but I hope some check like this won't bother us in the case of a real big bootstrap ?

I'll look at everything tomorrow, but just one question for now. For this test you had 0 txps on the network, right? Adding txps may make the times (potentially a lot) worse, and I think it would be nice to have some numbers on this.

**Comment by litchipi** [comment]
Bootstrapping fails with 10k txps:
```
2023-09-21T08:22:14.973719Z  WARN massa_bootstrap::client: Error while bootstrapping: general bootstrap error: `massa_consensus` error: there was an inconsistency between containers could not find latest block for thread 0
```

**Comment by litchipi** [comment]
Closing this PR in favor of #4453 , all the issues found and investigated here got documented on https://github.com/massalabs/massa/issues/4430

**Pull request closed without merging**
