### PR TITLE
Remove unecessary block clone

### PR DESCRIPTION
**Pull request by gterzian**
Close https://github.com/massalabs/massa/issues/2413

### CODE REVIEW

**Review by AurelienFT — DISMISSED** [review]

**Comment by gterzian** [comment]
@AurelienFT one moment I am still checking something...

**Comment by gterzian** [comment]
@AurelienFT ready for review, note the last commit got a bit more complicated...

**Review by AurelienFT — APPROVED** [review]

**Comment by gterzian** [comment]
@massalabs/core-team Can we get a second approval on this one please?

**Comment by qdrn** [comment]
> @massalabs/core-team Can we get a second approval on this one please?

I think one approval is enough.

**Comment by gterzian** [comment]
bors merge

**Pull request merged**
