### PR TITLE
Deduplicated get_status output.

### LINKED ISSUE #1378: Review get status output
In GitLab by @AureliaDolo

genesis timestamp and deltaf0 are duplicated in get status
* [ ] remove duplicates
* [ ] update docs/api.md

### PR DESCRIPTION
**Pull request by AureliaDolo**
Fix #1378

### CODE REVIEW

**Comment by AureliaDolo** [comment]
@yvan-sraka When should I update the api wiki page ?

**Comment by yvan-sraka** [comment]
Directly in the Wiki or in `/docs` git submodule it's the same :)

**Review by yvan-sraka — APPROVED** [review]

**Comment by AureliaDolo** [comment]
> Directly in the Wiki or in `/docs` git submodule it's the same :)

My docs folder is empty, should I do something specific ?

**Comment by yvan-sraka** [comment]
> My docs folder is empty, should I do something specific?

Yes! https://git-scm.com/book/en/v2/Git-Tools-Submodules

```
git submodule init
git submodule update
```

**Comment by AureliaDolo** [comment]
I will update the wiki when this is merged

bors merge

**Comment by AureliaDolo** [comment]
@yvan-sraka bors seems happy but hasn't merged

**Comment by yvan-sraka** [comment]
bors merge

**Pull request merged**
