### PR TITLE
Fix CI status badge

### PR DESCRIPTION
**Pull request by yvan-sraka**

### CODE REVIEW

**Comment by yvan-sraka** [comment]
bors merge

**Comment by AureliaDolo** [comment]
What does that do ?

**Comment by yvan-sraka** [comment]
[CI](https://github.com/massalabs/massa/actions/workflows/ci.yml?query=branch%3Amain)

**Comment by AureliaDolo** [comment]
> [CI](https://github.com/massalabs/massa/actions/workflows/ci.yml?query=branch%3Amain)

I don't understand your comment

**Comment by yvan-sraka** [comment]
What's the PR do is fixing this badge :)

**Pull request merged**
