### PR TITLE
WIP pool tests

### PR DESCRIPTION
**Pull request by adrien-zinger**
WIP: Start the development of pool tests.

- Add message passing between the execution mock and his receiver
- Add tests for the "get_block_operations" fonction
- Add tests for the "add_operation" in PoolOperation

Remove or comment temporary some old tests. Need to be checked if these test are still relevant to keep.

### CODE REVIEW

**Review by AurelienFT — APPROVED** [review]
For the moment I'm ok with the changes.

**Comment by damip** [comment]
@AurelienFT feel free to merge this if it is OK and doesn't break things

**Comment by AurelienFT** [comment]
We don't wait the other tests ? The PR is named "WIP"

**Comment by damip** [comment]
> We don't wait the other tests ? The PR is named "WIP"

@adrien-zinger  is on vacation, so this PR needs to be taken over

**Comment by AurelienFT** [comment]
Ok will do it after my testing but can merge this for now.

**Pull request merged**
