### PR TITLE
document hhasher

### PR DESCRIPTION
**Pull request by damip**

### CODE REVIEW

**Comment by AureliaDolo** [comment]
@yvan-sraka you had some remarks about that ?

**Comment by yvan-sraka** [comment]
Yes! I will rewrite all this soon :)

**Review by yvan-sraka — APPROVED** [review]

**Comment by yvan-sraka** [comment]
bors merge

**Review by adrien-zinger — APPROVED** [review]

**Comment by AureliaDolo** [comment]
bors merge

**Comment by yvan-sraka** [comment]
bors merge

**Pull request merged**
