### PR TITLE
Fix coverage

### PR DESCRIPTION
**Pull request by qdrn**

### CODE REVIEW

**Review by yvan-sraka — CHANGES_REQUESTED** [review]
The diff here do not change the behavior of `grcov` … The issue described here https://github.com/massalabs/massa/issues/2350 could be fixed by set up an `output-path` for LCOV file in this config file https://github.com/massalabs/massa/blob/main/.github/actions-rs/grcov.yml as described in the matching GitHub action README https://github.com/actions-rs/grcov#config

**Review by yvan-sraka — APPROVED** [review]
It's harmless, so we can give a try to it! Since @qdrn thinks to have spotted a regression here https://github.com/massalabs/massa/compare/441283585efa2760a1e0dd3426726a64639ae902..d32f1e1d9fcf104d7311614dc0e5395b60bd2847

**Review by damip — APPROVED** [review]

**Comment by qdrn** [comment]
bors merge

**Comment by qdrn** [comment]
@yvan-sraka I believe the problem was with the line `path-to-lcov: ${{ steps.coverage.outputs.report }}` as the step `coverage` did not exist anymore.

**Comment by yvan-sraka** [comment]
bors merge

**Pull request merged**
