### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by yvan-sraka**

### CODE REVIEW

**Comment by AureliaDolo** [comment]
Not sure how much this is usefull :/

**Comment by adrien-zinger** [comment]
This concerns the website or the node ? Or both of them ?

**Comment by AureliaDolo** [comment]
> This concerns the website or the node ? Or both of them ?
 
From what I understand this PR just takes the gitlab templates into github templates and there were not really used by anyone :/

**Comment by yvan-sraka** [comment]
bors merge

**Comment by yvan-sraka** [comment]
bors merge

**Pull request merged**
