### PR TITLE
Update `get_filtered_sc_output_event`  error handling in Massa client

### LINKED ISSUE #3395: Inappropriate warning in get_filtered_sc_output_event
```
command > get_filtered_sc_output_event operation_id=O12MeJnFrsXDZQ99xRhDXySptMRhAkJipEFDVJktCh5mvWzQxw
WARNING: 'operation_id' parameter was ignored because of wrong corresponding value
```

This kind of behavior shouldn't raise a warning but fail instead.

### PR DESCRIPTION
**Pull request by aoudiamoncef**
* [x] document all added functions
* [x] try in sandbox /simulation/labnet
* [x] unit tests on the added/changed features
  * [x] make tests compile
  * [x] make tests pass 
* [x] add logs allowing easy debugging in case the changes caused problems
* [x] if the API has changed, update the API specification

closes #3395

### CODE REVIEW

**Comment by aoudiamoncef** [comment]
The new output:

```shell
command > get_filtered_sc_output_event
command > get_filtered_sc_output_event toto
Error: invalid parameter: toto, type "help get_filtered_sc_output_event" to get the list of valid parameters
command > get_filtered_sc_output_event start=59,15
```

**Review by Leo-Besancon — APPROVED** [review]
Great, it is a lot cleaner this way.

My only question, are users expected to know the format of the arguments? Thinking about `Slot` especially, maybe users could try to use something like `get_filtered_sc_output_event start=(59,15)` instead.

**Comment by aoudiamoncef** [comment]
As a suer, I suffered to guess the format of `Slot` accepted by the client, I was obliged to look at the source code. I'll try to add this hint to help users

**Review by Leo-Besancon — APPROVED** [review]
Perfect!

**Pull request merged**
