### PR TITLE
Missing operation in OpenRPC

### PR DESCRIPTION
**Pull request by aoudiamoncef**
* [x] document all added functions
* [x] try in sandbox /simulation/labnet
* [x] unit tests on the added/changed features
  * [x] make tests compile
  * [x] make tests pass 
* [x] add logs allowing easy debugging in case the changes caused problems
* [x] if the API has changed, update the API specification

### CODE REVIEW

**Comment by aoudiamoncef** [comment]
This R fixes the broken OpenRPC playground

**Comment by aoudiamoncef** [comment]
Sorry, I tested it in the browser to be able to debug it so it changed the indentation

**Comment by aoudiamoncef** [comment]
Done

**Review by AurelienFT — APPROVED** [review]

**Comment by AurelienFT** [comment]
bors merge

**Pull request merged**
