### PR TITLE
Feature use get endorsement by xxx in api and client

### PR DESCRIPTION
**Pull request by AureliaDolo**

### CODE REVIEW

**Comment by AureliaDolo** [comment]
@qdrn @Noxhaa this will change the api

**Comment by qdrn** [comment]
Ok thanks for notifying. As long as it's retro-compatible it's not a big deal, we need to take special care when things change and there is a risk to break the explorer.

**Comment by AureliaDolo** [comment]
@yvan-sraka I'm not sure if there is still something to do in the client

**Comment by yvan-sraka** [comment]
I will check that! Maybe I can do that in follow-up?

**Review by yvan-sraka — APPROVED** [review]

**Comment by yvan-sraka** [comment]
I checked the client :heavy_check_mark:!

**Comment by yvan-sraka** [comment]
bors merge

**Pull request merged**
