### PR TITLE
Testnet 19 bootstrap timeout

### LINKED ISSUE #2649: Add a general timeout on bootstrap
## Context

The server in the bootstrap wait for message from client he is connected to.

## Problem

A client can ask to the server multiple data in loop to keep him alive. We should think of a way to avoid it. Multiple solutions I see :
- Ban node when asking multiple times the same info in short amount of time ?
- Ban node when cleint is connected for too long

### PR DESCRIPTION
**Pull request by Ben-PH**
closes #2649 

* [x] document all added functions
* [x] try in sandbox /simulation/labnet
* [ ] unit tests on the added/changed features
  * [ ] make tests compile
  * [ ] make tests pass 
* [x] add logs allowing easy debugging in case the changes caused problems
* [x] if the API has changed, update the API specification

### CODE REVIEW

**Comment by Ben-PH** [comment]
Things run fine in the labnet, but I'm yet to induce a ban on clients that overrun the timeout.

**Comment by Ben-PH** [comment]
So I managed to get a ban triggered for timeout, by doing the following:

deploying with commit `a5dfc32fb929b46756d40c6318871cc25fbbea79` - this sets the timeout to 2seconds

in `massa-bootstrap/src/client.rs` line 385, change from `bootstrap_config.max_bytes_read_write` to `200.0`

logs look like this
```
2023-01-17T10:55:47.691375Z DEBUG massa_bootstrap::server: awaiting on bootstrap of peer 90.55.149.65:49018
2023-01-17T10:55:48.839384Z DEBUG massa_bootstrap::server: Final state bootstrap cursor: Ongoing(Slot { period: 15, thread: 23 })
2023-01-17T10:55:48.839392Z DEBUG massa_bootstrap::server: Consensus blocks bootstrap cursor: Started
2023-01-17T10:55:48.840083Z DEBUG massa_bootstrap::server: Final state bootstrap cursor: Finished(Some(Slot { period: 15, thread: 23 }))
2023-01-17T10:55:48.840087Z DEBUG massa_bootstrap::server: Consensus blocks bootstrap cursor: Ongoing({ ... })
2023-01-17T10:55:48.840213Z DEBUG massa_bootstrap::server: Consensus bootstrap cursor length: 50
2023-01-17T10:55:48.941276Z DEBUG massa_bootstrap::server: Final state bootstrap cursor: Finished(Some(Slot { period: 15, thread: 23 }))
2023-01-17T10:55:48.941296Z DEBUG massa_bootstrap::server: Consensus blocks bootstrap cursor: Ongoing({ ... })
2023-01-17T10:55:48.942149Z DEBUG massa_bootstrap::server: Consensus bootstrap cursor length: 96
2023-01-17T10:55:48.943886Z DEBUG massa_bootstrap::server: Final state bootstrap cursor: Finished(Some(Slot { period: 15, thread: 23 }))
2023-01-17T10:55:48.943897Z DEBUG massa_bootstrap::server: Consensus blocks bootstrap cursor: Finished(None)
2023-01-17T10:55:49.692037Z DEBUG massa_bootstrap::server: bootstrap timeout for peer 90.55.149.65:49018
```

The errors aren't so useful client-side, so trying again with something a bit different

**Review by Eitu33 — APPROVED** [review]
Approving the timeout, do you plan on implementing the ban in this PR?

**Comment by Ben-PH** [comment]
I was under the impression that's already taken care of as per this comment: https://github.com/massalabs/massa/issues/2649#issuecomment-1180905317

**Pull request merged**
