### PR TITLE
Testnet 21

### PR DESCRIPTION
**Pull request by AurelienFT**

### CODE REVIEW

**Comment by Massembler** [comment]
Calibrating gas...
 Please do not commit before I finish. I will tell you when I'm done.

**Comment by AurelienFT** [comment]
@Massembler calibrate_gas

**Comment by Massembler** [comment]
Calibrating gas...
 Please do not commit before I finish. I will tell you when I'm done.

**Comment by AurelienFT** [comment]
@Massembler calibrate_gas

**Comment by Massembler** [comment]
Calibrating gas...
 Please do not commit before I finish. I will tell you when I'm done.

**Comment by AurelienFT** [comment]
@Massembler calibrate_gas

**Comment by Massembler** [comment]
Calibrating gas...
 Please do not commit before I finish. I will tell you when I'm done.

**Comment by Massembler** [comment]
Gas calibrated!

**Review by Leo-Besancon — APPROVED** [review]

**Comment by AurelienFT** [comment]
bors merge

**Pull request merged**
