### PR TITLE
Protocol: remove double block results type alias

### PR DESCRIPTION
**Pull request by gterzian**
Quick fix that I didn't want to get lost in a commit as part of https://github.com/massalabs/massa/pull/2233

### CODE REVIEW

**Review by yvan-sraka — DISMISSED** [review]

**Review by AureliaDolo — APPROVED** [review]

**Comment by gterzian** [comment]
bors merge

**Comment by gterzian** [comment]
>"Commits must have valid signatures."

Ok I will add the signature, in the meantime if someone wants to do a quick `git commit -a --amend` locally and force push to the branch, so it can be merged already, you are welcome. @yvan-sraka @AureliaDolo

**Comment by gterzian** [comment]
@yvan-sraka @AureliaDolo Ok I signed the commit, could you please re-approve?

**Review by yvan-sraka — APPROVED** [review]

**Review by AureliaDolo — APPROVED** [review]

**Comment by gterzian** [comment]
@AureliaDolo @yvan-sraka thanks!

bors merge

**Pull request merged**
