### PR TITLE
[FIX] Unit tests used to failed with timeout on macOS (#1826)

### PR DESCRIPTION
**Pull request by yvan-sraka**
`cargo test` fail on macOS in CI with a timeout error

### CODE REVIEW

**Comment by yvan-sraka** [comment]
bors merge

**Review by adrien-zinger — DISMISSED** [review]

**Comment by adrien-zinger** [comment]
I close this PR (look further #1826 )
bors merge

**Comment by AureliaDolo** [comment]
@yvan-sraka I'm not sure I understand what you did here

**Comment by yvan-sraka** [comment]
I try to highlight the fact that our CI fail on macOS (and that's a big issue) I can relax timing limits on macOS (with conditional compilation) but I'm not sure that it is what we want?

**Comment by AureliaDolo** [comment]
Definitely we don't want to relax timings, maybe it's the same kind of issue we had with tarpaulin ?

**Comment by yvan-sraka** [comment]
Maybe we should split tests that ensure correctness of algorithms VS benchmark that mesure how much a PR could induce performance changes.

**Comment by AureliaDolo** [comment]
We don't benchmark anything in the tests, it's just correctness.

**Comment by yvan-sraka** [comment]
How timeout could be a correctness concept? Is the code could still be correct but fail tests with relaxed timeout?

Timeout are for performance measuring or fail early, if our timeout values just make fail the app when we enable coverage or build on macOS there is an underlying issue of failing too early and give a false negative...

**Comment by AureliaDolo** [comment]
> How timeout could be a correctness concept? Is the code could still be correct but fail tests with relaxed timeout?
> 
> Timeout are for performance measuring or fail early, if our timeout values just make fail the app when we enable coverage or build on macOS there is an underlying issue of failing too early and give a false negative...

@yvan-sraka  I opened up #1950 to tackle that, so maybe we can close this pr for now ?

**Comment by damip** [comment]
@yvan-sraka  there is currently no benchmark test, only correctness tests, and those timeouts are part of correctness tests.
See https://github.com/massalabs/massa/issues/1950

**Comment by yvan-sraka** [comment]
bors merge

**Review by AureliaDolo — DISMISSED** [review]

**Comment by AureliaDolo** [comment]
bors merge

**Comment by yvan-sraka** [comment]
bors merge

**Comment by yvan-sraka** [comment]
bors merge

**Comment by yvan-sraka** [comment]
bors merge

**Review by AureliaDolo — COMMENTED** [review]
What changed since last time

**Comment by yvan-sraka** [comment]
> What changed since last time ?

The only test that fail is the one we fixed yesterday...

**Review by AureliaDolo — APPROVED** [review]

**Comment by AureliaDolo** [comment]
bors merge

**Comment by yvan-sraka** [comment]
@AureliaDolo https://github.com/massalabs/massa/runs/4592830856?check_suite_focus=true#step:5:647
```
thread 'tests::scenarios::test_run_node' panicked at 'called `Result::unwrap()` on an `Err` value: was not able to send command
```

**Comment by AureliaDolo** [comment]
> @AureliaDolo https://github.com/massalabs/massa/runs/4592830856?check_suite_focus=true#step:5:647
> 
> ```
> thread 'tests::scenarios::test_run_node' panicked at 'called `Result::unwrap()` on an `Err` value: was not able to send command
> ```

Maybe that will help a bit #2029

**Comment by yvan-sraka** [comment]
bors merge

**Comment by yvan-sraka** [comment]
bors merge

**Comment by yvan-sraka** [comment]
bors merge

**Pull request merged**
