### PR TITLE
refactor: Move api settings from massa models

### LINKED ISSUE #2419: Why api settings are in massa models
Move ApiSettings back to the massa-api crate

https://github.com/massalabs/massa/blob/96af89199979534edbc0993038bc4a436df86a74/massa-models/src/api.rs#L399-L405

### PR DESCRIPTION
**Pull request by aoudiamoncef**
close #2419

### CODE REVIEW

**Review by AurelienFT — DISMISSED** [review]
I don't see any problems with this and it make the code clearer.

**Comment by AurelienFT** [comment]
Sorry for the time before the review @aoudiamoncef. It causes merge conflicts. Can you resolve them before we merge please ?

**Review by AurelienFT — APPROVED** [review]

**Comment by aoudiamoncef** [comment]
@AurelienFT, I have some work in progress, should I create a PR before finishing ? you could create labels:  `do not merge` + `work in progress`

**Comment by AurelienFT** [comment]
Put the PR as "Draft" until you finished

**Comment by aoudiamoncef** [comment]
Hi @AurelienFT , it's finished, I'll fix it 🤝

**Comment by AurelienFT** [comment]
> Hi @AurelienFT , it's finished. ready to be merged

Sadly still not passing :(

**Review by AurelienFT — APPROVED** [review]
Thank you !

**Pull request merged**
