### PR TITLE
cargo update

### PR DESCRIPTION
**Pull request by modship**
* [x] document all added functions
* [ ] try in sandbox /simulation/labnet
  * [ ] if part of node-launch, checked using the `resync_check` flag
* [x] unit tests on the added/changed features
  * [x] make tests compile
  * [x] make tests pass 
* [x] add logs allowing easy debugging in case the changes caused problems
* [x] if the API has changed, update the API specification

### CODE REVIEW

**Comment by modship** [comment]
> this seems to have been done on main, I guess we should also merge main into testnet_26

Yes, we need to merge main into testnet_26 because the build fails after cargo update (there's a missing update for massa-proto).

**Comment by damip** [comment]
> > this seems to have been done on main, I guess we should also merge main into testnet_26
> 
> Yes, we need to merge main into testnet_26 because the build fails after cargo update (there's a missing update for massa-proto).

@aoudiamoncef can you sync with this ?

**Comment by modship** [comment]
> > > this seems to have been done on main, I guess we should also merge main into testnet_26
> > 
> > 
> > Yes, we need to merge main into testnet_26 because the build fails after cargo update (there's a missing update for massa-proto).
> 
> @aoudiamoncef can you sync with this ?

@damip https://github.com/massalabs/massa/pull/4358

**Comment by damip** [comment]
https://github.com/massalabs/massa/pull/4358 is done, so this can be closed ?

**Comment by modship** [comment]
> #4358 is done, so this can be closed ?

If TN26 will be merged into main, yes

**Comment by damip** [comment]
> > #4358 is done, so this can be closed ?
> 
> If TN26 will be merged into main, yes

it will, on release

**Pull request closed without merging**
