### PR TITLE
Add a `beta` cargo feature 🌈

### PR DESCRIPTION
**Pull request by yvan-sraka**

### CODE REVIEW

**Review by AureliaDolo — COMMENTED** [review]
That means that for now beta is the same as without feature ?

**Comment by yvan-sraka** [comment]
> That means that for now beta is the same as without feature ?

Until we have any `if cfg!("beta")` or `#[cfg(beta)]` in code, yes!

**Review by AureliaDolo — APPROVED** [review]

**Comment by AureliaDolo** [comment]
bors merge

**Review by damip — APPROVED** [review]
LGTM.
We'll start using it for in the next episode

**Comment by yvan-sraka** [comment]
bors merge

**Comment by AureliaDolo** [comment]
bors merge

**Pull request merged**
