### PR TITLE
Check static config Hash on bootstrap.

### LINKED ISSUE #1992: Check hash of protocol related config at bootstrap
Instead of just checking the version we could hash all protocol related config and make sure the hashes match. Anyway, if this is not ok that will lead to desynchronization.

Since #1848 is merged that should be quite easy

### PR DESCRIPTION
**Pull request by AureliaDolo**
Fix #1992 

I still have to figure out how to compute that hash for real

### CODE REVIEW

**Comment by damip** [comment]
This is not necessary anymore given the new config system.
All the critical settings are now hardcoded in the source code, including the version number.
So checking the version number is enough.
Also if someone wants to cheat, they can always do it by sending a fake hash.

**Review by damip — CHANGES_REQUESTED** [review]
to be closed

**Comment by AureliaDolo** [comment]
This is useful in case someone altered their settings.rs and built the binaries by themselves. Preventing them from joining the main network would limit the number of nodes that will produce only invalid blocks

**Comment by damip** [comment]
If people already altered the code, they will probably also comment out the verification system. Too much work and future maintenance (adding every new parameter to the verification process) for very marginal benefit. Closing

**Pull request closed without merging**
