### PR TITLE
Ben/boot loop ctrlc hotfix

### PR DESCRIPTION
**Pull request by Ben-PH**
* [ ] document all added functions
* [x] try in sandbox /simulation/labnet
* [x] unit tests on the added/changed features
  * [x] make tests compile
  * [x] make tests pass 
* [ ] add logs allowing easy debugging in case the changes caused problems
* [ ] if the API has changed, update the API specification

### CODE REVIEW

**Comment by Ben-PH** [comment]
status: running tests locally. Ran it on testnet: bootstrapped fine, handled ctrl-c fine.

**Comment by Ben-PH** [comment]
...also upgrades the bootstrap error messages a touch

**Review by AurelienFT — APPROVED** [review]
Nice improvement. Tokio is removed again 🎉

**Comment by AurelienFT** [comment]
bors merge

**Pull request merged**
