### PR TITLE
Remove useless dependencies in Cargo.toml

### PR DESCRIPTION
**Pull request by yvan-sraka**
Close https://github.com/massalabs/massa/issues/1256

### CODE REVIEW

**Comment by yvan-sraka** [comment]
I can re-add them only as dev dependencies? (it will make builds faster)

**Comment by damip** [comment]
This PR broke the test compilation:

```
error[E0433]: failed to resolve: use of undeclared crate or module `serde_json`
   --> crypto/src/hash.rs:226:26
    |
226 |         let serialized = serde_json::to_string(&hash).unwrap();
    |                          ^^^^^^^^^^ use of undeclared crate or module `serde_json`

error[E0433]: failed to resolve: use of undeclared crate or module `serde_json`
   --> crypto/src/hash.rs:227:28
    |
227 |         let deserialized = serde_json::from_str(&serialized).unwrap();
    |                            ^^^^^^^^^^ use of undeclared crate or module `serde_json`

error[E0433]: failed to resolve: use of undeclared crate or module `serde_json`
   --> crypto/src/signature.rs:780:13
    |
780 |             serde_json::to_string(&private_key).expect("could not serialize private key");
    |             ^^^^^^^^^^ use of undeclared crate or module `serde_json`

error[E0433]: failed to resolve: use of undeclared crate or module `serde_json`
   --> crypto/src/signature.rs:782:13
    |
782 |             serde_json::from_str(&serialized).expect("could not deserialize private key");
    |             ^^^^^^^^^^ use of undeclared crate or module `serde_json`

error[E0433]: failed to resolve: use of undeclared crate or module `serde_json`
   --> crypto/src/signature.rs:792:13
    |
792 |             serde_json::to_string(&public_key).expect("Could not serialize public key");
    |             ^^^^^^^^^^ use of undeclared crate or module `serde_json`

error[E0433]: failed to resolve: use of undeclared crate or module `serde_json`
   --> crypto/src/signature.rs:794:13
    |
794 |             serde_json::from_str(&serialized).expect("could not deserialize public key");
    |             ^^^^^^^^^^ use of undeclared crate or module `serde_json`

error[E0433]: failed to resolve: use of undeclared crate or module `serde_json`
   --> crypto/src/signature.rs:806:13
    |
806 |             serde_json::to_string(&signature).expect("could not serialize signature key");
    |             ^^^^^^^^^^ use of undeclared crate or module `serde_json`

error[E0433]: failed to resolve: use of undeclared crate or module `serde_json`
   --> crypto/src/signature.rs:808:13
    |
808 |             serde_json::from_str(&serialized).expect("could not deserialize signature key");
    |             ^^^^^^^^^^ use of undeclared crate or module `serde_json`
```

**Comment by yvan-sraka** [comment]
I know ... as noticed earlier in the comments! I will fix that before merging (because bors won't let me otherwise :)

**Review by AureliaDolo — APPROVED** [review]
There were quite a few useless dependencies

**Comment by yvan-sraka** [comment]
bors merge

**Pull request merged**
