### PR TITLE
New shiny deployment :sparkles: 

### PR DESCRIPTION
**Pull request by yvan-sraka**

### CODE REVIEW

**Comment by AureliaDolo** [comment]
Not sure I understand why the sanity has not passed

**Comment by yvan-sraka** [comment]
> Not sure I understand why the sanity has not passed

Because https://github.com/massalabs/massa-deploy is a private repository and it fails to checkout ...

**Comment by AureliaDolo** [comment]
> Because https://github.com/massalabs/massa-deploy is a private repository and it fails to checkout ...

So @damip we can make that repo public ?

**Comment by qdrn** [comment]
We could probably put the repo public.

Not sure my concern about bootstrap has been taken into account tho.

**Comment by AureliaDolo** [comment]
> Not sure my concern about bootstrap has been taken into account tho.

Where did you express it ? Can you link it here ? Thanks ! :)

**Comment by qdrn** [comment]
It was in discord. https://discord.com/channels/761151090673844244/897861461416763493/918555076702916648

**Comment by AureliaDolo** [comment]
> It was in discord. https://discord.com/channels/761151090673844244/897861461416763493/918555076702916648

> For the initial deployment, there is no issue but if there is an update, will it update one by one to ensure there will always be a bootstrap server

@qdrn I quickly translated your comment, feel free to edit

**Comment by yvan-sraka** [comment]
> For the initial deployment, there is no issue but if there is an update, will it update one by one to ensure there will always be a bootstrap server

@qdrn I could use two strategies:

A. wait X min (with X = 5 ?) between the deployment of each server, to ensure that there is enough time to bootstrap and to not deploy everything simultaneously (or having a list of "bootstrap serve" that are deployed with a delay of X minute after the other server?)

B. let control to the user (here it's a bit hacky but if you have other ideas tell me) by deploying half of the server with the tag TEST.X and the other half with the branch testnet update ? (or we could have one tag per server ?)

**Comment by qdrn** [comment]
I think waiting 5 minutes between each server should be enough.

**Comment by yvan-sraka** [comment]
> I think waiting 5 minutes between each server should be enough.

I implemented it here https://github.com/massalabs/massa-deploy/commit/01fe9bbee06971aa97fbbe2111e4f0c822564f3e :wink:!

**Review by AureliaDolo — APPROVED** [review]

**Review by qdrn — COMMENTED** [review]
You want to add the changes to `cd.yml` later ?

**Comment by qdrn** [comment]
> Everything is ready to merge, we just have to set up the rights [GitHub Secrets](https://github.com/massalabs/massa/settings/environments), and we're all good!

Am I missing something or the change to `cd.yml` have been reverted ? Are they in another branch ?

I can add the GitHub Secrets.

**Comment by yvan-sraka** [comment]
> Am I missing something or the change to `cd.yml` have been reverted ? Are they in another branch ?

There are here https://github.com/massalabs/massa-deploy/commit/01fe9bbee06971aa97fbbe2111e4f0c822564f3e (in a git submodule of Massa main repository)

**Comment by yvan-sraka** [comment]
bors merge

**Pull request merged**
