### PR TITLE
Add Gitpod integration

### LINKED ISSUE #2585: Gitpod integration
IMHO it could be interesting to add [Gitpod](https://www.gitpod.io/docs/languages/rust). It'll make easier the process of contribution, specially small ones(50 hours peer month).

I'm waiting for feedback

### PR DESCRIPTION
**Pull request by aoudiamoncef**
resolves #2585

### CODE REVIEW

**Comment by damip** [comment]
@aoudiamoncef  wainting for your confirmation to merge :)

**Comment by aoudiamoncef** [comment]
Waiting for @AurelienFT tests

**Comment by damip** [comment]
let's merge it :)

**Review by damip — APPROVED** [review]

**Comment by damip** [comment]
bors merge

**Pull request merged**
