### PR TITLE
Rework consensus and graph

### PR DESCRIPTION
**Pull request by AurelienFT**
* [x] document all added functions
* [x] try in sandbox /simulation/labnet
* [x] unit tests on the added/changed features
  * [x] make tests compile
  * [x] make tests pass 
* [x] add logs allowing easy debugging in case the changes caused problems
* [x] if the API has changed, update the API specification

### CODE REVIEW

**Comment by AurelienFT** [comment]
Still few points to address tomorrow on formatting, verifications, etc but the PR works.

**Comment by AurelienFT** [comment]
Labnet node stopped without errors after few cycles : 
```
2022-10-25T11:14:12.527472Z DEBUG massa_execution_worker::execution: execute_candidate_slot: executing slot=(period: 757, thread: 3) target=None
2022-10-25T11:14:12.581657Z DEBUG massa_factory_worker::endorsement_factory: endorsement LoYPQF7TwtTBqauexHwycqKzhQR9jXa99EEhiKwVvQtoFyirZ created at slot (period: 757, thread: 18) by address A1qS7hYYYvSc61KMPWVi124k44hZAJSXKPvboYg1m2YiSDveWAp
2022-10-25T11:14:12.605213Z  INFO massa_factory_worker::block_factory: block oN29zrGTakxGe3gHxMAW655WjzZ3B65dZUvkR7FTVnEaHpExG created at slot (period: 757, thread: 7) by address A1qS7hYYYvSc61KMPWVi124k44hZAJSXKPvboYg1m2YiSDveWAp
2022-10-25T11:14:12.694980Z DEBUG massa_execution_worker::execution: execute_candidate_slot: execution finished
2022-10-25T11:14:12.728827Z DEBUG massa_graph_2_worker::state::process_commands: received block oN29zrGTakxGe3gHxMAW655WjzZ3B65dZUvkR7FTVnEaHpExG for slot (period: 757, thread: 7)
2022-10-25T11:14:12.777622Z DEBUG massa_execution_worker::execution: execute_candidate_slot: execution state applied
2022-10-25T11:14:12.803979Z DEBUG massa_factory_worker::endorsement_factory: endorsement 28UeLnt2Bao8hHzgL1mwShXjwWtH5x1wwXKagpqsVKYvjMiBvB created at slot (period: 757, thread: 18) by address A1qS7hYYYvSc61KMPWVi124k44hZAJSXKPvboYg1m2YiSDveWAp
2022-10-25T11:14:12.879222Z DEBUG massa_execution_worker::worker: Execution loop triggered, input_data = stop=false, finalized={}, blockclique=None, readonly=RequestQueue { max_items: 10000, queue: [] }
2022-10-25T11:14:12.983455Z DEBUG massa_factory_worker::endorsement_factory: endorsement 2TZSHHUPDHtpQi2jgYbro912uVw7EALfhwxg7BVZUAsmJ1eHf2 created at slot (period: 757, thread: 18) by address A1qS7hYYYvSc61KMPWVi124k44hZAJSXKPvboYg1m2YiSDveWAp
2022-10-25T11:14:13.304980Z DEBUG massa_execution_worker::execution: execute_candidate_slot: executing slot=(period: 757, thread: 4) target=None
2022-10-25T11:14:13.519162Z DEBUG massa_execution_worker::execution: execute_candidate_slot: execution finished
```

**Review by Eitu33 — COMMENTED** [review]
Looks good to me but I do not consider myself qualified to approve this PR

**Comment by AurelienFT** [comment]
PR has been tested on labnet.

**Review by damip — APPROVED** [review]

**Pull request merged**
