### PR TITLE
Upgrade runtime to 0.4.3

### PR DESCRIPTION
**Pull request by adrien-zinger**
Upgrade wasmer version.

### CODE REVIEW

**Review by AureliaDolo — APPROVED** [review]

**Review by qdrn — APPROVED** [review]

**Comment by qdrn** [comment]
bors merge

**Comment by damip** [comment]
bors merge

**Comment by damip** [comment]
@yvan-sraka  can you take a look ?

**Comment by yvan-sraka** [comment]
This branch must not contain merge commits.

https://docs.github.com/articles/about-protected-branches

**Comment by yvan-sraka** [comment]
```shell
git checkout MyUnalignedBranch
git pull -r origin main
git push -f
```

**Comment by yvan-sraka** [comment]
bors merge

**Pull request merged**
