### PR TITLE
Add emoji :crab: Fix #1854

### LINKED ISSUE #1308: fix config
In GitLab by @AureliaDolo

### LINKED ISSUE #1854: [client] Highligth most used commands
In GitLab by @Noxha

Yea, reordering is enough, ideally with some clear split "-----------" and maybe title.
No space maybe between the paragraph though, as a long list of commands is not handy to read on a terminal if it's bigger than the screen (better to see all of them without having to scroll)

_Originally posted by @massa-bot in https://github.com/massalabs/massa/issues/1307#issuecomment-966947421_

### PR DESCRIPTION
**Pull request by AureliaDolo**

### CODE REVIEW

**Comment by AureliaDolo** [comment]
It's a quick hack to highlight most used and useful commands

**Comment by yvan-sraka** [comment]
I think it's cool! ⭐

**Comment by damip** [comment]
can you post a screenshot to see how it renders :) ?

**Comment by AureliaDolo** [comment]
image
@damip

**Review by yvan-sraka — APPROVED** [review]

**Review by adrien-zinger — APPROVED** [review]
:sparkles:

**Review by damip — CHANGES_REQUESTED** [review]
The fact that there are multiple different emojis requires a legend. I was quite confused trying to figure out what each of them meant...

If you want to highlight some commands, I vote for just using a single type of emoji

**Comment by AureliaDolo** [comment]
> The fact that there are multiple different emojis requires a legend. I was quite confused trying to figure out what each of them meant...

We can add that add the start of the client
:star: for most used
:green_square: for money
:purple_circle: for one time use

I think that we can't highlight every command that is highlighted here so if you want to keep only one emoji, which commands do you think are the most important ones ?

**Comment by damip** [comment]
I feel this brings more bloat and confusion than it improves clarity

**Comment by AureliaDolo** [comment]
I close that, it's just a quick fix

**Pull request closed without merging**
