### PR TITLE
Fix bootstrap retry

### PR DESCRIPTION
**Pull request by AurelienFT**
* [x] document all added functions
* [x] try in sandbox /simulation/labnet
* [x] unit tests on the added/changed features
  * [x] make tests compile
  * [x] make tests pass 
* [x] add logs allowing easy debugging in case the changes caused problems
* [x] if the API has changed, update the API specification

### CODE REVIEW

**Comment by AurelienFT** [comment]
Fix #3412

**Comment by AurelienFT** [comment]
Tried to make a bootstrap test but it's too complicated and takes too much time. Will test it in labnet with modified node.

**Comment by AurelienFT** [comment]
I have tested on labnet with tests line of https://github.com/massalabs/massa/pull/3576/commits/31e2e60f2381f0cd5d891d7e3c7e88319cb5e341 this allow to make the first bootstrap fail and wait so much that the second fail for too old slot and after reset everything went well and the final hash at slot was good

**Review by Eitu33 — APPROVED** [review]
Do we have an open issue about the possibility of retrying bootstrap from the downloaded state of a previously failed bootstrap or is that not something we want to handle?

**Comment by AurelienFT** [comment]
> Do we have an open issue about the possibility of retrying bootstrap from the downloaded state of a previously failed bootstrap or is that not something we want to handle?

It should already be possible if it's not a too old slot. For a too old slot I don't think it's possible

**Pull request merged**
