### PR TITLE
robustify test

### PR DESCRIPTION
**Pull request by damip**

### CODE REVIEW

**Review by adrien-zinger — APPROVED** [review]

**Comment by adrien-zinger** [comment]
bors merge

**Comment by adrien-zinger** [comment]
```zsh
failures:
    tests::scenarios106::test_dep_in_back_order_with_max_dependency_blocks
```

**Comment by damip** [comment]
pfiou... let's retry xD

**Comment by damip** [comment]
bors merge

**Comment by AureliaDolo** [comment]
I opened up #2188 as I'm not quite sure to understand what makes you decide how to relax timeouts

**Pull request merged**
