### PR TITLE
Set snake case for enums

### LINKED ISSUE #2795: Harmonize JSON response output for enums/structs
Actually, enum are serialized with Rust name : 
```json
{
  "content": {
...
    "op": {
      "Transaction": {
        "amount": "0.000950028",
        "recipient_address": "A1Czd9sRp3mt2KU9QBEEZPsYxRq9TisMs1KnV4JYCe7Z4AAVinq"
      }
    }
  },
...
}
```

It should be in snake case : 

```json
{
  "content": {
...
    "op": {
      "transaction": {
        "amount": "0.000950028",
        "recipient_address": "A1Czd9sRp3mt2KU9QBEEZPsYxRq9TisMs1KnV4JYCe7Z4AAVinq"
      }
    }
  },
...
}
```

Solution : 

```rust
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum OperationType {
    /// transfer coins from sender to recipient
    Transaction {
        /// recipient address
        recipient_address: Address,
        /// amount
        amount: Amount,
    },
...
}
```

### PR DESCRIPTION
**Pull request by aoudiamoncef**
closes #2795

### CODE REVIEW

**Comment by AurelienFT** [comment]
I think we need to update tooling before merging this ? cc @qdrn

**Comment by qdrn** [comment]
> I think we need to update tooling before merging this ? cc @qdrn

Yes. If you merge this one you should make issues in the repos that will be affected by this change (massa-web3 and explorer).

**Comment by damip** [comment]
I think we should group this with the API refactoring project

**Comment by aoudiamoncef** [comment]
@AurelienFT we should merge this asap

**Comment by AurelienFT** [comment]
> @AurelienFT we should merge this asap

Maybe we should only make it for v2 to avoid breaking too much things in V1 API.

**Pull request closed without merging**
