### PR TITLE
fix internal error serde

### PR DESCRIPTION
**Pull request by modship**
* [ ] document all added functions
* [ ] try in sandbox /simulation/labnet
  * [ ] if part of node-launch, checked using the `resync_check` flag
* [ ] unit tests on the added/changed features
  * [ ] make tests compile
  * [ ] make tests pass 
* [ ] add logs allowing easy debugging in case the changes caused problems
* [ ] if the API has changed, update the API specification

### CODE REVIEW

**Comment by Leo-Besancon** [comment]
@modship can you rebase on `pre_mainnet_wip` branch please? So we can create a 27.2 from this directly

**Comment by bilboquet** [comment]
I've tested this branch, and it solves the problem described in #4555

**Review by Leo-Besancon — APPROVED** [review]
Nice solve, this seems hard to catch! Approved once rebased on pre_mainnet_wip.
Do you think there is potentially other cases where something like this may happen?

**Comment by aoudiamoncef** [comment]
We have to reuse existing tests like we did here and add Serde usecase to be sure

**Comment by modship** [comment]
> @modship can you rebase on `pre_mainnet_wip` branch please? So we can create a 27.2 from this directly

done

**Pull request merged**
