### PR TITLE
Improve operations batching

### PR DESCRIPTION
**Pull request by gterzian**
Possible fix for https://github.com/massalabs/massa/issues/2522

Changes:

1. `on_operations_announcements_received` now only adds to the buffer.
2. buffer is processed at each timer interval.
3. A command is only send to network if a permit can be acquired.
4. An item in the buffer is only removed if sending the message at 3 was successful.
5. If the buffer is full when receiving an announcement is received, we drop the oldest one.

### CODE REVIEW

**Comment by gterzian** [comment]
@adrien-zinger Here is a start, please take a look. Feel free to make changes, I'm done for the day.

**Comment by gterzian** [comment]
Ok I'd say we try to merge this one, and then we can also consider doing [this](https://github.com/massalabs/massa/issues/2522#issuecomment-1097684672) as a follow-up.

**Comment by adrien-zinger** [comment]
I'm not sure,that change totally the original algorithm of Seb no? We should see with him :)

**Review by adrien-zinger — APPROVED** [review]
Yes, that can be interesting to try!!

**Comment by gterzian** [comment]
Do we want to merge this as is, or first deploy the branch for testing on the labnet? @adrien-zinger @damip 

I think we should add some tests also because some should have failed with these changes.

**Comment by adrien-zinger** [comment]
> Do we want to merge this as is, or first deploy the branch for testing on the labnet? @adrien-zinger @damip
> 
> I think we should add some tests also because some should have failed with these changes.

It's to @damip to take the responsibility :rofl:. In my opinion, the current change don't break the network, and we want to iterate fast. :slightly_smiling_face:

**Comment by gterzian** [comment]
@AurelienFT can you take a look please? I think we can merge it after...

**Review by AurelienFT — APPROVED** [review]

**Comment by AurelienFT** [comment]
bors merge

**Pull request merged**
