### PR TITLE
Feature/typos 1

### PR DESCRIPTION
**Pull request by sydhds**
* [ ] document all added functions
* [ ] try in sandbox /simulation/labnet
  * [ ] if part of node-launch, checked using the `resync_check` flag
* [ ] unit tests on the added/changed features
  * [ ] make tests compile
  * [ ] make tests pass 
* [ ] add logs allowing easy debugging in case the changes caused problems
* [ ] if the API has changed, update the API specification

### CODE REVIEW

**Comment by sydhds** [comment]
One remaining error reported by typos:

```
Some(grpc_model::operation_type::Type::ExecutSc(execute_sc));
```

Fixing the typo on grpc enum Type name should not break compatibility? @Leo-Besancon @bilboquet

**Comment by Leo-Besancon** [comment]
> One remaining error reported by typos:
> 
> ```
> Some(grpc_model::operation_type::Type::ExecutSc(execute_sc));
> ```
> 
> Fixing the typo on grpc enum Type name should not break compatibility right? @Leo-Besancon @bilboquet

I think we have to be careful about:
- Request params from the JSON-RPC API
- Maybe response params (but less important)
- For GRPC, I think it's ok if done in a certain way (for example, the order of the elements do not change), but maybe @bilboquet or @modship can confirm

I don't see other cases that raise issues

**Comment by modship** [comment]
> > One remaining error reported by typos:
> > ```
> > Some(grpc_model::operation_type::Type::ExecutSc(execute_sc));
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Fixing the typo on grpc enum Type name should not break compatibility right? @Leo-Besancon @bilboquet
> 
> I think we have to be careful about:
> 
> * Request params from the JSON-RPC API
> * Maybe response params (but less important)
> * For GRPC, I think it's ok if done in a certain way (for example, the order of the elements do not change), but maybe @bilboquet or @modship can confirm
> 
> I don't see other cases that raise issues

enum name type come from massa-proto so we should update it if we modify

**Comment by sydhds** [comment]
> One remaining error reported by typos:
> 
> ```
> Some(grpc_model::operation_type::Type::ExecutSc(execute_sc));
> ```
> 
> Fixing the typo on grpc enum Type name should not break compatibility right? @Leo-Besancon @bilboquet

Try to serialize with the old name versus the new name and it does not change :)

Waiting for https://github.com/massalabs/massa-proto/pull/67 to be merged

**Comment by Leo-Besancon** [comment]
> > > One remaining error reported by typos:
> > > ```
> > > Some(grpc_model::operation_type::Type::ExecutSc(execute_sc));
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Fixing the typo on grpc enum Type name should not break compatibility right? @Leo-Besancon @bilboquet
> > 
> > 
> > Try to serialize with the old name versus the new name and it does not change :)
> > Waiting for [massalabs/massa-proto#67](https://github.com/massalabs/massa-proto/pull/67) to be merged
> 
> The CI of massa-proto reports a breaking change and it's kinda difficult to see the impact in the tooling. Maybe drop this and keep it that way? @Leo-Besancon @bilboquet

This would be fine with me.

**Review by bilboquet — APPROVED** [review]
it looking good

**Pull request closed without merging**
