### PR TITLE
Add panic handler, shutdown on panic

### PR DESCRIPTION
**Pull request by gterzian**
FIX https://github.com/massalabs/massa/issues/2840

### CODE REVIEW

**Comment by gterzian** [comment]
ready for review @damip

**Review by damip — COMMENTED** [review]
@gterzian LGTM, let's add it to the other binary as well (massa-client)

**Comment by gterzian** [comment]
@damip Ok, just needs an approval now...

**Review by damip — APPROVED** [review]
nice !

**Comment by damip** [comment]
bors merge

**Pull request merged**
