### PR TITLE
Prune shared storage

### PR DESCRIPTION
**Pull request by gterzian**
Close https://github.com/massalabs/massa/issues/2308

### CODE REVIEW

**Comment by gterzian** [comment]
@damip I'm wondering how we should go about pruning discarded final blocks. Should we perhaps move that to execution, to after they've been executed?

**Comment by gterzian** [comment]
@damip ping on the above.

**Comment by gterzian** [comment]
How about the following:

1. When graph prunes an active block, it doesn't delete it(unless see below), instead it marks it as `pruned`. 
2. When execution executes a block, it marks it as `executed`. 

Then, when execution executes a blocked marked `pruned`, it deletes it. 

And when graph prunes a blocks marked `executed`, it also deletes it. 

cc @damip

**Comment by AureliaDolo** [comment]
I may be missing something but where are you pruning old final blocks ?

**Comment by gterzian** [comment]
Closing this, as the work has been done in https://github.com/massalabs/massa/pull/2428

**Comment by gterzian** [comment]
Closing this, as the work has been done in https://github.com/massalabs/massa/pull/2428

**Pull request closed without merging**
