### PR TITLE
All bootstrap unit tests are now serial

### PR DESCRIPTION
**Pull request by sydhds**
* [ ] document all added functions
* [ ] try in sandbox /simulation/labnet
  * [ ] if part of node-launch, checked using the `resync_check` flag
* [ ] unit tests on the added/changed features
  * [ ] make tests compile
  * [ ] make tests pass 
* [ ] add logs allowing easy debugging in case the changes caused problems
* [ ] if the API has changed, update the API specification

### CODE REVIEW

**Comment by Leo-Besancon** [comment]
Bootstrap tests are passing on my windows

**Comment by Eitu33** [comment]
On Mac OS:

```shell
running 9 tests
test tests::binders::test_binders_double_send_server_works ... ok
test tests::binders::test_partial_msg ... ok
test tests::binders::test_binders_try_double_send_client_works ... ok
test tests::binders::test_binders ... ok
test tests::binders::test_bandwidth ... ok
test tests::binders::test_client_drip_feed ... ok
test tests::scenarios::test_bootstrap_accept_err ... ok
test tests::scenarios::test_bootstrap_server has been running for over 60 seconds
test tests::scenarios::test_bootstrap_whitelist has been running for over 60 seconds
test tests::scenarios::test_bootstrap_server ... ok
test tests::scenarios::test_bootstrap_whitelist ... ok

test result: ok. 9 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 82.75s

pthread lock: Invalid argument
error: test failed, to rerun pass `--lib`

Caused by:
  process didn't exit successfully: `/Users/thomas/Professional/massa/target/debug/deps/massa_bootstrap-31c6f13287377f3f` (signal: 6, SIGABRT: process abort signal)
```

**Comment by damip** [comment]
I have very repeatably the same as @Eitu33 on my ubuntu 23.04:

With this (to be faster it activates only one test): `cargo test --features testing test_bootstrap_whitelist`

Half of the time it crashes with 

```
running 1 test
test tests::scenarios::test_bootstrap_whitelist ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 8 filtered out; finished in 0.28s

pthread lock: Invalid argument
error: test failed, to rerun pass `-p massa_bootstrap --lib`
```

**Review by modship — COMMENTED** [review]
There are a few comments to remove.

**Review by modship — APPROVED** [review]

**Comment by sydhds** [comment]
> There are a few comments to remove.

Code cleanup done :)

**Comment by damip** [comment]
CI still seems to fail

**Comment by AurelienFT** [comment]
Noooooooo

**Comment by AurelienFT** [comment]
OMG PRESS THE GREEN BUTTON

**Comment by damip** [comment]
> OMG PRESS THE GREEN BUTTON

PRESSED :tada:

**Pull request merged**
