### PR TITLE
Consensus: add test for processing of execute sc operation

### LINKED ISSUE #2075: Test: sc operation processing in block reception
Todo scenario

### PR DESCRIPTION
**Pull request by gterzian**
Close #2075

### CODE REVIEW

**Comment by gterzian** [comment]
Also clean-up some tests.... ready for review @AureliaDolo

**Review by AureliaDolo — APPROVED** [review]
Nice catch ! I guess cleaning up the tests would be great.

The new test looks good.

**Comment by AureliaDolo** [comment]
bors merge

**Comment by AureliaDolo** [comment]
bors merge

**Pull request merged**
