### PR TITLE
Add link to code documentation in README

### PR DESCRIPTION
**Pull request by yvan-sraka**
[Rendered](https://github.com/massalabs/massa/blob/doc-badge/README.md)

### CODE REVIEW

**Comment by AureliaDolo** [comment]
What does that do ?

**Comment by yvan-sraka** [comment]
It add  to `README.md` the badge:

[Docs](https://massalabs.github.io/massa/massa_node/)

**Review by AureliaDolo — APPROVED** [review]
:sparkles:

**Comment by yvan-sraka** [comment]
bors merge

**Pull request merged**
