### PR TITLE
Fix coverage, don't test dependencies

### PR DESCRIPTION
**Pull request by yvan-sraka**

### CODE REVIEW

**Review by adrien-zinger — APPROVED** [review]

**Comment by adrien-zinger** [comment]
bors merge

**Comment by yvan-sraka** [comment]
bors merge

**Comment by yvan-sraka** [comment]
bors merge

**Comment by yvan-sraka** [comment]
Bors merge

**Comment by AureliaDolo** [comment]
@yvan-sraka 

```
 warning: an associated function with this name may be added to the standard library in the future
   --> massa-consensus/src/pos.rs:522:37
    |
522 |         let bits_u8_len = n_entries.div_ceil(&u8::BITS) as usize;
    |                                     ^^^^^^^^
    |
    = note: `#[warn(unstable_name_collisions)]` on by default
    = warning: once this associated item is added to the standard library, the ambiguity may cause an error or change in behavior!
    = note: for more information, see issue #48919 <https://github.com/rust-lang/rust/issues/48919>
    = help: call with fully qualified syntax `num::Integer::div_ceil(...)` to keep using the current method
    = help: add `#![feature(int_roundings)]` to the crate attributes to enable `core::num::<impl u32>::div_ceil`
```

And bors is failing because the testnet is over yay :cactus:

**Comment by yvan-sraka** [comment]
I suggest disabling this test until auto-deployment with flavours! 🌈

**Comment by AureliaDolo** [comment]
> I suggest disabling this test until auto-deployment with flavours! rainbow

Seems like it's done in #2049

**Comment by yvan-sraka** [comment]
bors merge

**Review by AureliaDolo — APPROVED** [review]

**Comment by AureliaDolo** [comment]
bors merge

**Comment by AureliaDolo** [comment]
bors merge

**Pull request merged**
