### PR TITLE
Add final cursor to exec stats

### LINKED ISSUE #4142: final cursor in `get_status` in client
The client returns the current speculative execution cursor. It should also (and more importantly) return the final one !

### PR DESCRIPTION
**Pull request by aoudiamoncef**
* [x] document all added functions
* [ ] try in sandbox /simulation/labnet
* [x] unit tests on the added/changed features
  * [x] make tests compile
  * [x] make tests pass 
* [x] add logs allowing easy debugging in case the changes caused problems
* [x] if the API has changed, update the API specification

resolves #4142

### CODE REVIEW

**Review by AurelienFT — DISMISSED** [review]

**Comment by aoudiamoncef** [comment]
@AurelienFT the CI is failing, is It related to this PR or something else ?

**Comment by AurelienFT** [comment]
> @AurelienFT the CI is failing... I should fixe the tests

It's because you updated the version of massa-sc-runtime in the cargo lock. Revert this change and it should pass.

**Comment by aoudiamoncef** [comment]
> > @AurelienFT the CI is failing... I should fixe the tests
> 
> It's because you updated the version of massa-sc-runtime in the cargo lock. Revert this change and it should pass.

I found it hihih, just rollback the cargo lock file

**Review by AurelienFT — APPROVED** [review]

**Comment by aoudiamoncef** [comment]
bors merge

**Pull request merged**
