### PR TITLE
send only required blocks to bootstrap

### PR DESCRIPTION
**Pull request by damip**

### CODE REVIEW

**Comment by damip** [comment]
I used the opportunity to clean up a whole bunch of useless and performance-hindering mess that was introduced recently in the block graph bootstrap graph/block import/export system

**Review by adrien-zinger — APPROVED** [review]
@damip Look good to me, I asked myself about how many blocks we were speaking about while bootstrapping before? VS the number of blocks required.

**Review by AureliaDolo — APPROVED** [review]

**Comment by damip** [comment]
> @damip Look good to me, I asked myself about how many blocks we were speaking about while bootstrapping before? VS the number of blocks required.

initialy, about 100, after the optims about 1500

**Comment by damip** [comment]
bors merge

**Pull request merged**
