### PR TITLE
Preparing an upgrade of sc-runtime version to 0.3.0

### PR DESCRIPTION
**Pull request by adrien-zinger**

### CODE REVIEW

**Comment by damip** [comment]
Was the tag created on the massa-sc-runtime ?

Could we use the opportunity to rename it ? because "assembly_simulator" is extremely misleading

**Comment by adrien-zinger** [comment]
> Was the tag created on the massa-sc-runtime ?
> 
> Could we use the opportunity to rename it ? because "assembly_simulator" is extremely misleading

I'm waiting for some pull request to be merged. Ok 👌 I'll rename also into massa-sc-runtime for this version

**Review by damip — APPROVED** [review]

**Comment by adrien-zinger** [comment]
Duplicated !! (merged in #2145

**Comment by damip** [comment]
@adrien-zinger  why was this closed ?

**Pull request closed without merging**
