### PR TITLE
Fix logging filter

### PR DESCRIPTION
**Pull request by AurelienFT**
Fix https://github.com/massalabs/massa/issues/2353

### CODE REVIEW

**Review by AureliaDolo — APPROVED** [review]

**Review by yvan-sraka — APPROVED** [review]

**Comment by yvan-sraka** [comment]
bors merge

**Comment by AurelienFT** [comment]
@yvan-sraka I can reproduce in local the test failing. I saw to you have tried to relaunch on an other PR but it doesn't seems to be CI (and things) related.

**Comment by yvan-sraka** [comment]
> @yvan-sraka I can reproduce in local the test failing. I saw to you have tried to relaunch on an other PR but it doesn't seems to be CI (and things) related.

Mistake on my side, I was thinking that a fix was already merged in `main` 😅

**Comment by AurelienFT** [comment]
> Mistake on my side, I was thinking that a fix was already merged in `main` 😅

There is already a PR with test fixed ?

**Comment by yvan-sraka** [comment]
> There is already a PR with test fixed ?

Not yet ... @qdrn working on it!

**Review by damip — APPROVED** [review]

**Comment by damip** [comment]
@AurelienFT  Can you merge main into this PR ? It should repair the CI !

**Comment by damip** [comment]
bors merge

**Pull request merged**
