### PR TITLE
Fix undeterministic owner_addresses

### PR DESCRIPTION
**Pull request by adrien-zinger**
Change owner_addresses into deterministically ordered data structure.

### CODE REVIEW

**Review by damip — APPROVED** [review]

**Comment by AureliaDolo** [comment]
bors merge

**Comment by AureliaDolo** [comment]
test_update_latest_final_block_cmd_notification is failing on mcos

**Comment by adrien-zinger** [comment]
> test_update_latest_final_block_cmd_notification is failing on mcos

WHyyyy

**Comment by damip** [comment]
@adrien-zinger  https://github.com/massalabs/massa/pull/2183

**Review by yvan-sraka — APPROVED** [review]
Nice 👌

**Comment by damip** [comment]
merged into https://github.com/massalabs/massa/pull/2196
closing this PR

**Pull request closed without merging**
