### PR TITLE
Fix warning in massa-hash

### PR DESCRIPTION
**Pull request by adrien-zinger**
Rename hash::hash to hash::from

### CODE REVIEW

**Review by gterzian — APPROVED** [review]
LGTM. What was the warning?

**Review by AureliaDolo — COMMENTED** [review]
These warnings can be fixed, if you want
pos.rs L81 L87 L93 L202 L208 use of `ok_or` followed by a function call
pos.r2 l 187 struct `RollCounts` has a public `len` method, but no `is_empty` method
operation_pool.rs L244 avoid using `collect()` when not needed
operation_pool.rs L330 use of `ok_or` followed by a function call

Why did you rename Hash::hash into Hash::from ?

**Comment by yvan-sraka** [comment]
bors merge

**Comment by adrien-zinger** [comment]
> These warnings can be fixed, if you want pos.rs L81 L87 L93 L202 L208 use of `ok_or` followed by a function call pos.r2 l 187 struct `RollCounts` has a public `len` method, but no `is_empty` method operation_pool.rs L244 avoid using `collect()` when not needed operation_pool.rs L330 use of `ok_or` followed by a function call
> 
> Why did you rename Hash::hash into Hash::from ?

Hash::hash had a redondant warning. I think "from" is more idiomatic. It's my side quest to resolve all warnings in massa world :superhero: I resolve one file at a time!

**Pull request merged**
