### PR TITLE
Set-up `tracing-subscriber` for instrumentation with `tokio-console`

### PR DESCRIPTION
**Pull request by yvan-sraka**
Before merge it, I will hide the changes required by `tokio-tracing` behind an `cargo run --feature instrument`?

_Originally posted by @yvan-sraka in https://github.com/massalabs/massa/issues/2190#issuecomment-1032341384_

### CODE REVIEW

**Review by AureliaDolo — DISMISSED** [review]
LGTM but maybe add a little bit of doc somewhere to recall that this feature exist and what it does

**Review by AureliaDolo — APPROVED** [review]

**Comment by damip** [comment]
This looks good. Only problem: it will require maintenance whenever we change/rename the crates (eg in the refactoring). And if we don't really end up using it, it will become a burden and we will have to eventually remove it. What do you think ? Is it worth the long-term burden ?

**Comment by yvan-sraka** [comment]
> This looks good. Only problem: it will require maintenance whenever we change/rename the crates (eg in the refactoring). And if we don't really end up using it, it will become a burden and we will have to eventually remove it. What do you think ? Is it worth the long-term burden ?

If you're talking about maintaining feature propagation in `Cargo.toml`, rename a crate would just mean search replace crate name, so yes it worth it :)

**Comment by damip** [comment]
> > This looks good. Only problem: it will require maintenance whenever we change/rename the crates (eg in the refactoring). And if we don't really end up using it, it will become a burden and we will have to eventually remove it. What do you think ? Is it worth the long-term burden ?
> 
> If you're talking about maintaining feature propagation in `Cargo.toml`, rename a crate would just mean search replace crate name, so yes it worth it :)

ok then :)

**Review by damip — APPROVED** [review]

**Comment by yvan-sraka** [comment]
bors merge

**Review by adrien-zinger — DISMISSED** [review]

**Review by AureliaDolo — APPROVED** [review]

**Comment by yvan-sraka** [comment]
bors merge

**Comment by yvan-sraka** [comment]
This https://github.com/massalabs/massa/pull/2275 need to be merged first!

**Comment by yvan-sraka** [comment]
bors merge

**Review by AureliaDolo — DISMISSED** [review]

**Review by adrien-zinger — APPROVED** [review]

**Comment by yvan-sraka** [comment]
bors merge

**Review by AureliaDolo — APPROVED** [review]

**Review by adrien-zinger — APPROVED** [review]

**Comment by yvan-sraka** [comment]
bors merge

**Pull request merged**
