### PR TITLE
Protocol: add test for the propagation of operations 

### PR DESCRIPTION
**Pull request by gterzian**
Fix https://github.com/massalabs/massa/issues/3033

### CODE REVIEW

**Comment by gterzian** [comment]
@massalabs/core-team How do we want to fix this? I propose the following:

1. Add a return value of "relevant blocks" to `pool.add_operations`. 
2. Re-add the `propagate` flag to `protocol_worker.note_operations_from_node`, where the flag is true if we receive the operations outside of a block. 
3. Have protocol announce all the relevant operations returned by 1, if the flag at 2 is `true`.

**Comment by gterzian** [comment]
Will close in favor of https://github.com/massalabs/massa/pull/3035

**Comment by damip** [comment]
https://github.com/massalabs/massa/pull/3035 was merged, would be cool to adapt this test by rebasing on main to ensure that no regression happens

**Comment by gterzian** [comment]
I've updated the tests to reflect the fact that we now propagate operations in all cases. Ready for review @damip @AurelienFT

**Review by AurelienFT — APPROVED** [review]

**Comment by AurelienFT** [comment]
bors merge

**Comment by AurelienFT** [comment]
bors merge

**Comment by AurelienFT** [comment]
bors cancel

**Comment by AurelienFT** [comment]
The CI seems to run in loop on this PR and #3014. Will rerun it one by one this night. We need to keep bors queue clean for testnet release right now

**Comment by AurelienFT** [comment]
bors merge

**Pull request merged**
