### PR TITLE
Clean dependencies

### LINKED ISSUE #4450: remove risky/heavy dependencies that are not in use (eg. Quiche) @aoudiamoncef

### PR DESCRIPTION
**Pull request by aoudiamoncef**
* [x] document all added functions
* [x] try in sandbox /simulation/labnet
  * [ ] if part of node-launch, checked using the `resync_check` flag
* [x] unit tests on the added/changed features
  * [x] make tests compile
  * [x] make tests pass 
* [x] add logs allowing easy debugging in case the changes caused problems
* [x] if the API has changed, update the API specification

fix  #4450

### CODE REVIEW

**Review by Leo-Besancon — APPROVED** [review]
A little spring cleaning goes a long way 🎉

**Comment by aoudiamoncef** [comment]
@Leo-Besancon I upgraded, let's see If the CI passes

**Review by Leo-Besancon — APPROVED** [review]
I think we didn't miss anything there :)

**Comment by aoudiamoncef** [comment]
Bors merge

**Pull request merged**
