### PR TITLE
Add tests serialization

### PR DESCRIPTION
**Pull request by AurelienFT**
massa-serialization has 93% coverage on this PR.

### CODE REVIEW

**Review by sydhds — COMMENTED** [review]
Looks good but I see that only u64 varint is tested here. Coud we use parametric test and test u16 / u32 varint too?

**Comment by AurelienFT** [comment]
> Looks good but I see that only u64 varint is tested here. Coud we use parametric test and test u16 / u32 varint too?

As they are all generating using the same code I didn't think it was useful but can do. I don't know anything about parametric test will try otherwise I just make more tests

**Comment by AurelienFT** [comment]
@sydhds I have made a macro to make parameterized test. I re-ask the review. Ty for the suggestion it was cool to do.

**Review by sydhds — DISMISSED** [review]

**Review by Leo-Besancon — DISMISSED** [review]
If you can add a quick comment above the macro to explain what it tests for each type, it would be better than reading through the macro, but the macro isn't horrible so it's good to be merged as is.

**Comment by AurelienFT** [comment]
> If you can add a quick comment above the macro to explain what it tests for each type, it would be better than reading through the macro, but the macro isn't horrible so it's good to be merged as is.

Thank you. Done.

**Review by Leo-Besancon — APPROVED** [review]
Thanks :)

**Comment by AurelienFT** [comment]
bors merge

**Pull request merged**
