### PR TITLE
Clean up massa-network

### PR DESCRIPTION
**Pull request by AurelienFT**
This PR clean the code of massa-network : 

- Remove `ToSend` enum that was introduced for shared storage and old serialization format that was incompatible. Now it's useless
- So now we send directly Message to binders so that the serialization/deserialization is only in binders.
- Remove the chunks of block informations has it's already chunk by the parent function and also was bugged because the `send_data` call was in a too much inner loop.
- Pass full object to network and therefore remove usage of storage and fetch elements directly in protocol.
- So the two enum for blocks infos was regrouped.

This also fix a bug of nodes that disconnect because the serializing was bugged because the `send_data` was in the wrong loop and so it sent only the first element in the first message that serialize the full size. of the list.

This PR has been tested in simulator.

### CODE REVIEW

**Comment by damip** [comment]
@AurelienFT  Good catch for the bug, and very welcome code improvements !

@gterzian FYI

**Review by gterzian — APPROVED** [review]
LGTM, I actually need the fix in https://github.com/massalabs/massa/pull/2916

**Comment by gterzian** [comment]
bors merge

**Comment by AurelienFT** [comment]
Can't use bors CI don't pass.

**Comment by AurelienFT** [comment]
bors cancel

**Pull request merged**
