### PR TITLE
Execution: improve worker

### PR DESCRIPTION
**Pull request by gterzian**

### CODE REVIEW

**Comment by gterzian** [comment]
In response to https://github.com/massalabs/massa/pull/2249#discussion_r812720320

**Comment by gterzian** [comment]
@damip ready for review. 

The idea is to make the loop simpler by having one point at the point where one waits for the next event, and having the rest be about processing that event. 

Also a few other small things(each is a separate commit).

**Comment by damip** [comment]
Ok I got it :) 
Implemented in the original PR. Thanks

**Comment by gterzian** [comment]
Ok, closing this one then.

**Pull request closed without merging**
