### PR TITLE
secure pools

### PR DESCRIPTION
**Pull request by damip**
* [x] document all added functions
* [x] try in sandbox /simulation/labnet
* [x] unit tests on the added/changed features
  * [x] make tests compile
  * [x] make tests pass 
* [x] add logs allowing easy debugging in case the changes caused problems
* [x] if the API has changed, update the API specification

### CODE REVIEW

**Comment by AurelienFT** [comment]
@damip if it's ready for review can you fix the CI ? Or you want us to handle that if you don't have much time.

**Comment by damip** [comment]
> @damip if it's ready for review can you fix the CI ? Or you want us to handle that if you don't have much time.

Sorry no it's not ready yet, marking as draft

**Comment by AurelienFT** [comment]
@aoudiamoncef Can you check the API and GRPC part plz ?

**Comment by damip** [comment]
@aoudiamoncef cna you take a look at the api and grpc related changes ?

**Review by aoudiamoncef — APPROVED** [review]

**Review by AurelienFT — APPROVED** [review]

**Comment by AurelienFT** [comment]
Still some tests that fail

**Review by AurelienFT — APPROVED** [review]

**Pull request merged**
