### PR TITLE
Updated concurrency.md

### PR DESCRIPTION
**Pull request by AureliaDolo**
[Rendered](https://github.com/massalabs/massa/blob/Fix-%231376-Update-concurrency.md-file-after-api-refactoring/docs/concurrency.md)

### CODE REVIEW

**Comment by yvan-sraka** [comment]
What's the purpose of this document? Is this dev docs or user wiki?

If it's dev docs I would prefer to have it as a doc comment in for e.g. `massa-node`!

**Comment by AureliaDolo** [comment]
> What's the purpose of this document? Is this dev docs or user wiki?
> 
> If it's dev docs I would prefer to have it as a doc comment in for e.g. `massa-node`!

I don't remember :/

@gterzian I think you first wrote this file ?

**Review by adrien-zinger — CHANGES_REQUESTED** [review]
I think the indents are broken :smile:
I don't understand how to read this documentation. Maybe you  could use mermaid for this?

**Comment by AureliaDolo** [comment]
> I think the indents are broken smile I don't understand how to read this documentation. Maybe you could use mermaid for this?

The goal was to have some quite easy to read, easy to update view of how each part interacts with other.

Indeed a graph may be more readable than a list :)

**Review by adrien-zinger — APPROVED** [review]
Lovely graphs

**Comment by adrien-zinger** [comment]
bors merge

**Review by gterzian — APPROVED** [review]
great, thanks!

**Comment by yvan-sraka** [comment]
bors cancel

**Comment by yvan-sraka** [comment]
bors merge

**Pull request merged**
