### PR TITLE
Protocol tests: block propagation

### PR DESCRIPTION
**Pull request by gterzian**
FIX https://github.com/massalabs/massa/issues/2907

### CODE REVIEW

**Comment by gterzian** [comment]
@massalabs/core-team Note that there was a problem with shutting down the protocol worker, which is fixed by https://github.com/massalabs/massa/pull/2916/commits/fe15c25366623564b43185c654946d4be937315e

**Comment by damip** [comment]
> @massalabs/core-team Note that there was a problem with shutting down the protocol worker, which is fixed by [fe15c25](https://github.com/massalabs/massa/commit/fe15c25366623564b43185c654946d4be937315e)

Yes it was also identified and corrected (among a couple other problems) in the quick end to end testing done yesterday by Aurelien: https://github.com/massalabs/massa/pull/2920

**Comment by damip** [comment]
A rebase on release_testnet_14 is needed for this branch

**Comment by gterzian** [comment]
note the following error:

```
---- tests::endorsements_scenarios::test_protocol_propagates_endorsements_to_active_nodes stdout ----
thread 'tests::endorsements_scenarios::test_protocol_propagates_endorsements_to_active_nodes' panicked at 'Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.', massa-protocol-exports/src/protocol_controller.rs:159:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

cc @massalabs/core-team

**Comment by damip** [comment]
> note the following error:
> 
> ```
> ---- tests::endorsements_scenarios::test_protocol_propagates_endorsements_to_active_nodes stdout ----
> thread 'tests::endorsements_scenarios::test_protocol_propagates_endorsements_to_active_nodes' panicked at 'Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.', massa-protocol-exports/src/protocol_controller.rs:159:14
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> cc @massalabs/core-team

https://docs.rs/tokio/latest/tokio/sync/mpsc/struct.Sender.html#method.blocking_send

"This function panics if called within an asynchronous execution context."
We should have both sync and async versions of the methods tha tuse tokio mpsc senders when they need to be called from heterogenous contexts.

**Comment by gterzian** [comment]
> We should have both sync and async versions of the methods that use tokio mpsc senders when they need to be called from heterogenous contexts.

For now just calling the command from a spawned thread in the tests... cc @AurelienFT

**Comment by gterzian** [comment]
@AurelienFT After rebasing off of your network, changes, there are 7 new tests failing, perhaps you can look at it? 

```
failures:
    tests::ban_nodes_scenarios::test_protocol_bans_node_sending_block_header_with_invalid_signature
    tests::ban_nodes_scenarios::test_protocol_bans_node_sending_operation_with_invalid_signature
    tests::ban_nodes_scenarios::test_protocol_does_not_asks_for_block_from_banned_node_who_propagated_header
    tests::ban_nodes_scenarios::test_protocol_does_not_send_blocks_when_asked_for_by_banned_node
    tests::ban_nodes_scenarios::test_protocol_removes_banned_node_on_disconnection
    tests::cache_scenarios::test_noting_block_does_not_panic_with_zero_max_node_known_blocks_size
    tests::in_block_operations_scenarios::test_protocol_sends_blocks_with_operations_to_consensus
```

Also I think it's a good idea to make sure all tests compile, since currently we're not running full CI on branches merging into `release_testnet_14`. (see https://github.com/massalabs/massa/pull/2916/commits/94a700d03e7c73b765f574e4a89d3f64fb9a2a15)

Besides this, the PR is ready for review, and it contains the critical test you asked for @damip

**Comment by AurelienFT** [comment]
> @AurelienFT After rebasing off of your network changes, there are 7 new tests failing, perhaps you can look at it?
> 
> ```
> failures:
>     tests::ban_nodes_scenarios::test_protocol_bans_node_sending_block_header_with_invalid_signature
>     tests::ban_nodes_scenarios::test_protocol_bans_node_sending_operation_with_invalid_signature
>     tests::ban_nodes_scenarios::test_protocol_does_not_asks_for_block_from_banned_node_who_propagated_header
>     tests::ban_nodes_scenarios::test_protocol_does_not_send_blocks_when_asked_for_by_banned_node
>     tests::ban_nodes_scenarios::test_protocol_removes_banned_node_on_disconnection
>     tests::cache_scenarios::test_noting_block_does_not_panic_with_zero_max_node_known_blocks_size
>     tests::in_block_operations_scenarios::test_protocol_sends_blocks_with_operations_to_consensus
> ```
> 
> Also I think it's a good idea to locally make sure all tests compile, since currently we're not running full CI on branches merging into `release_testnet_14`. (see [94a700d](https://github.com/massalabs/massa/commit/94a700d03e7c73b765f574e4a89d3f64fb9a2a15))
> 
> Besides this, the PR is ready for review, and it contains the critical test you asked for @damip

Ok will check them and try to make them pass.

**Comment by AurelienFT** [comment]
The tests has been broken by #2936 not by network changes but I have fixed them. There is still one left. Working on it. cc @gterzian

**Comment by gterzian** [comment]
@AurelienFT Ok I hand it over to you now. Note that the test I mentioned are not ignored, there are others that are still ignored to be addressed in a follow-up.

Reverted the change to storage, and fixed the relevant tests...

**Comment by gterzian** [comment]
@AurelienFT Ok thanks! Let me check that last test then...

**Comment by AurelienFT** [comment]
> @AurelienFT Ok thanks! Let me check that last test then...

I think the problem is that the operation isn't stored in storage.

**Comment by gterzian** [comment]
> I think the problem is that the operation isn't stored in storage.

Yes correct.

**Review by AurelienFT — APPROVED** [review]

**Comment by gterzian** [comment]
Ok ready for review, I can continue on the still ignored tests, and I think we should first try to merge this.

**Pull request merged**
