### PR TITLE
Replace Status by is_final in ExportCompiledBlockStatus.

### LINKED ISSUE #1187: ExportCompiledBlock contains Status instead of ExportBlockStatus
In GitLab by @AureliaDolo

ExportCompiledBlock should contain ExportBlockStatus

### PR DESCRIPTION
**Pull request by AureliaDolo**
Fix #1187

### CODE REVIEW

**Review by yvan-sraka — DISMISSED** [review]
LGTM

**Comment by yvan-sraka** [comment]
bors merge

**Comment by yvan-sraka** [comment]
@adrien-zinger @AureliaDolo it fails to run the node on windows https://github.com/massalabs/massa/runs/4457806267?check_suite_focus=true#step:6:135 ... why?!

**Comment by AureliaDolo** [comment]
Seems like it can't be closed. Sometimes if there is a lot of stuff that's happening it can make up to 30 secs to stop the node after the command has been executed in the client

**Comment by yvan-sraka** [comment]
> Seems like it can't be closed. Sometimes if there is a lot of stuff that's happening it can make up to 30 secs to stop the node after the command has been executed in the client

So relax a bit timeout, maybe making 5 attempts instead of 3 may be the right solution?

**Comment by AureliaDolo** [comment]
bors merge

**Comment by AureliaDolo** [comment]
@yvan-sraka @adrien-zinger seems weird that it only fails here right ?

**Review by yvan-sraka — APPROVED** [review]

**Comment by yvan-sraka** [comment]
bors merge

**Pull request merged**
