### PR TITLE
Update block creation test.

### PR DESCRIPTION
**Pull request by AureliaDolo**

### CODE REVIEW

**Comment by AureliaDolo** [comment]
And that test is failing

**Comment by damip** [comment]
ExecuteSC serialization and deserialization are both incorrect. I will correct that today, will try to merge the correction in here to see if it repairs the test

**Comment by AureliaDolo** [comment]
> ExecuteSC serialization and deserialization are both incorrect. I will correct that today, will try to merge the correction in here to see if it repairs the test

the test succeeded once max gas per block was updated

**Review by damip — APPROVED** [review]

**Comment by damip** [comment]
merged main in the branch after correcting ExecutionSC problems in main

**Comment by damip** [comment]
bors merge

**Pull request merged**
