### PR TITLE
List required active blocks refactoring

### PR DESCRIPTION
**Pull request by Eitu33**
* [x] document all added functions
* [x] try in labnet
* [x] make tests compile
* [x] make tests pass 
* [x] add logs allowing easy debugging in case the changes caused problems

### CODE REVIEW

**Review by AurelienFT — APPROVED** [review]

**Comment by AurelienFT** [comment]
bors merge

**Comment by damip** [comment]
The bootstrap test fails in the CI

**Comment by AurelienFT** [comment]
bors merge

**Comment by AurelienFT** [comment]
that's strange that it fails sometimes, we already saw this error on a precedent PR but don't have any bug on the testnet similar :/

**Comment by damip** [comment]
It does consistently fail. We should investigate

**Comment by AurelienFT** [comment]
> It does consistently fail. We should investigate

Yes !

**Review by AurelienFT — APPROVED** [review]

**Comment by AurelienFT** [comment]
bors merge

**Pull request merged**
