### PR TITLE
`% cargo clippy --fix`

### PR DESCRIPTION
**Pull request by yvan-sraka**

### CODE REVIEW

**Comment by AureliaDolo** [comment]
Is it expected that is didn''t fixed all clippy warnings?

**Comment by yvan-sraka** [comment]
Yup the tools fix only "obvious" fixes that didn't require review! For the warnings left we have to go by hand ...

**Review by AureliaDolo — APPROVED** [review]

**Comment by AureliaDolo** [comment]
At least it gets rid of useless clones

**Comment by yvan-sraka** [comment]
bors merge

**Pull request merged**
