### PR TITLE
Refactor/#3269 Remove blockId from API call response when not found

### PR DESCRIPTION
**Pull request by modship**
* [ ] document all added functions
* [ ] try in sandbox /simulation/labnet
* [ ] unit tests on the added/changed features
  * [X] make tests compile
  * [X] make tests pass 
* [ ] add logs allowing easy debugging in case the changes caused problems
* [ ] if the API has changed, update the API specification
image

Before : 
image

After : 
image

### CODE REVIEW

**Comment by AurelienFT** [comment]
Thanks again for your contribution @modship could you test on test.17 now ?

**Comment by modship** [comment]
@AurelienFT i think @aoudiamoncef have making change by himself on his commit a0ad9e63b7370f019c6512758ff9a63b68d8a48c

**Comment by aoudiamoncef** [comment]
> @AurelienFT i think @aoudiamoncef have making change by himself on his commit [a0ad9e6](https://github.com/massalabs/massa/commit/a0ad9e63b7370f019c6512758ff9a63b68d8a48c)

You could continue on this. I rollback my changes.

**Comment by aoudiamoncef** [comment]
Hi @modship,

We revisite `get_block` method and simplify it to `get_blocks` to be consistant with others Massa methods. 

As a result, this PR is not needed anymore. 

Thanks for your contribution and see you for a new one's ASAP

**Pull request closed without merging**
