### PR TITLE
Unify balances

### PR DESCRIPTION
**Pull request by AurelienFT**
See https://github.com/massalabs/massa/discussions/2952

### CODE REVIEW

**Comment by damip** [comment]
What needs to be added now is to prevent non-smartcontract addresses from hosting bytecode

**Comment by AurelienFT** [comment]
> Good work !! What needs to be added now is to prevent non-smartcontract addresses from hosting bytecode

Done in this commit : https://github.com/massalabs/massa/pull/3012/commits/08bdb2282d89263bc69a06ea2a671bff720de266

**Comment by AurelienFT** [comment]
@damip and @Eitu33 this is now ready for review !

**Review by Eitu33 — APPROVED** [review]
Absolutely amazing 👍 💰 🚀

**Pull request merged**
