### PR TITLE
remove staking lock

### LINKED ISSUE #4389: Node stuck
**Context:**
- Labnet network with 10k txps
- My local node have 20 staking address (Previous network and test)

When i try to remove multiple staking address with massa-client `node_stop_staking XXX...` my node stuck and doesn't receive any block for a while.
Then it unblocks and works normally

### PR DESCRIPTION
**Pull request by modship**
* [ ] document all added functions
* [ ] try in sandbox /simulation/labnet
  * [ ] if part of node-launch, checked using the `resync_check` flag
* [ ] unit tests on the added/changed features
  * [ ] make tests compile
  * [ ] make tests pass 
* [ ] add logs allowing easy debugging in case the changes caused problems
* [ ] if the API has changed, update the API specification

### CODE REVIEW

**Comment by modship** [comment]
the problem must be the same with `add_keypairs()`

**Comment by modship** [comment]
this solution works but we need to call manually save() with read_lock after remove_addresses

**Comment by damip** [comment]
can you rebase it on main ?

**Comment by modship** [comment]
> can you rebase it on main ?

done :)

**Review by damip — APPROVED** [review]

**Comment by damip** [comment]
bors merge

**Pull request merged**
