### PR TITLE
log generated execution events

### PR DESCRIPTION
**Pull request by damip**
log generated execution events for debugging purposes

### CODE REVIEW

**Review by AureliaDolo — COMMENTED** [review]
Won't that be lost in the other logs ?

**Comment by damip** [comment]
> Won't that be lost in the other logs ?

there are very few "info" logs, only startup, block creation, slot selection

**Review by AureliaDolo — APPROVED** [review]

**Comment by AureliaDolo** [comment]
I unlinked the issues as merging this would have solved them and this is just a quick fix

**Comment by damip** [comment]
bors merge

**Pull request merged**
