### PR TITLE
Update all dependencies include sc-runtime to round gas costs

### PR DESCRIPTION
**Pull request by AurelienFT**
* [x] document all added functions
* [ ] try in sandbox /simulation/labnet
* [x] unit tests on the added/changed features
  * [ ] make tests compile
  * [ ] make tests pass 
* [x] add logs allowing easy debugging in case the changes caused problems
* [x] if the API has changed, update the API specification

### CODE REVIEW

**Comment by AurelienFT** [comment]
@Massembler help

**Comment by AurelienFT** [comment]
@Massembler help

**Comment by Massembler** [comment]
Hello! I'm Massembler, a bot that help us in our development at Massa. Here are some commands you can use on comments on PR: calibrate_gas

**Comment by AurelienFT** [comment]
@Massembler calibrate_gas

**Comment by Massembler** [comment]
Calibrating gas...
 Please do not commit before I finish. I will tell you when I'm done.

**Comment by AurelienFT** [comment]
@Massembler calibrate_gas

**Comment by Massembler** [comment]
Calibrating gas...
 Please do not commit before I finish. I will tell you when I'm done.

**Comment by Massembler** [comment]
Gas calibrated!

**Comment by AurelienFT** [comment]
@damip the gas for ABI like call etc don't have the "non-compilation" optimization. Do you want me to artificially downgrade this one or we will not spam this ?

**Review by Eitu33 — APPROVED** [review]

**Pull request merged**
