### PR TITLE
Implement `get_addresses_bytecode` in JsonRPC

### LINKED ISSUE #4474: Add `get_address_bytecode` ABI to the JsonRPC API
Add get_address_bytecode ABI to the JSONRPSEE API:

```
get_address_bytecode:
    
    Arguments:
       * address: the address to get the bytecode for
       * final: optional boolean (default: false)
   
    Return value:
       * error if the address does not exist
       * the bytecode of the address in its candidate state if final=false or its final state if final=true (the execution controller's query_state function can be used to get the info). The binary bytecode should be encoded the same way as the other binary data we return elsewhere through JSONRPSEE 
```

### PR DESCRIPTION
**Pull request by aoudiamoncef**
* [x] document all added functions
* [ ] try in sandbox /simulation/labnet
  * [ ] if part of node-launch, checked using the `resync_check` flag
* [x] unit tests on the added/changed features
  * [x] make tests compile
  * [x] make tests pass 
* [x] add logs allowing easy debugging in case the changes caused problems
* [x] if the API has changed, update the API specification

closes #4474

### CODE REVIEW

**Comment by aoudiamoncef** [comment]
> @modship I'm struggling with tests due to compilation issues

Fixed

**Comment by aoudiamoncef** [comment]
@modship the PR is ready to be merged

**Review by modship — DISMISSED** [review]

**Comment by aoudiamoncef** [comment]
@modship I don't have any error locally even with the same command...

**Review by modship — APPROVED** [review]

**Comment by aoudiamoncef** [comment]
bors merge

**Pull request merged**
