### PR TITLE
fix: get_blockclique_block_by_slot panic

### PR DESCRIPTION
**Pull request by aoudiamoncef**
* [x] document all added functions
* [x] try in sandbox /simulation/labnet
* [x] unit tests on the added/changed features
  * [x] make tests compile
  * [x] make tests pass 
* [x] add logs allowing easy debugging in case the changes caused problems
* [x] if the API has changed, update the API specification

### CODE REVIEW

**Comment by damip** [comment]
Duplicate of https://github.com/massalabs/massa/pull/3169 ?

**Comment by AurelienFT** [comment]
> Duplicate of #3169 ?

@aoudiamoncef found that my fix didn't fixed it because the node still crash

**Comment by damip** [comment]
> > Duplicate of #3169 ?
> 
> @aoudiamoncef found that my fix didn't fixed it because the node still crash

Oh and this does fix it ?

**Comment by aoudiamoncef** [comment]
I tried it with my node, yes it's works 😅

**Review by damip — APPROVED** [review]

**Comment by damip** [comment]
bors merge

**Pull request merged**
