### PR TITLE
Fix a compilation error (maybe temporary)

### PR DESCRIPTION
**Pull request by adrien-zinger**
It seems that we need to change something quick! The standard library will pass over

```bash
   Compiling massa_consensus v0.1.0 (/home/adrien/Documents/repos/massa/massa-consensus)
warning: an associated function with this name may be added to the standard library in the future
   --> massa-consensus/src/pos.rs:522:37
    |
522 |         let bits_u8_len = n_entries.div_ceil(&u8::BITS) as usize;
    |                                     ^^^^^^^^
    |
    = note: `#[warn(unstable_name_collisions)]` on by default
    = warning: once this associated item is added to the standard library, the ambiguity may cause an error or change in behavior!
    = note: for more information, see issue #48919 <https://github.com/rust-lang/rust/issues/48919>
    = help: call with fully qualified syntax `num::Integer::div_ceil(...)` to keep using the current method
    = help: add `#![feature(int_roundings)]` to the crate attributes to enable `core::num::<impl u32>::div_ceil`
```

Opt for the fully qualified syntax

### CODE REVIEW

**Comment by damip** [comment]
As you prefer :) I would have voted for `#![feature(int_roundings)]` but there are pros and cons to both solutions

**Review by gterzian — APPROVED** [review]
LGTM

**Review by damip — DISMISSED** [review]

**Review by damip — APPROVED** [review]

**Comment by adrien-zinger** [comment]
Bors merge

**Comment by damip** [comment]
bors merge

**Comment by damip** [comment]
@adrien-zinger  this one can be solved now by cherrypicking

**Comment by AureliaDolo** [comment]
> @adrien-zinger this one can be solved now by cherrypicking

@damip has it been cherry picked ? Is someone working one that ?

**Comment by damip** [comment]
bors merge

**Comment by damip** [comment]
bors merge

**Comment by damip** [comment]
bors merge

**Comment by damip** [comment]
bors merge

**Comment by adrien-zinger** [comment]
This is already merged in cautious bassoon. You can close this pr

**Pull request closed without merging**
