### PR TITLE
Fix #1315: use Cargo profiles to speed up CI

### LINKED ISSUE #1315: Faster CI
In GitLab by @yvan-sraka

We can use the profit of Cargo profiles to speed up CI:

https://doc.rust-lang.org/cargo/reference/profiles.html

(for example by building our module in debug mode while compiling `serde` and other dependencies we trust with all optimizations)

```toml
[profile.dev.package.serde]
opt-level = 3
[profile.dev.package."*"]
opt-level = 2
```

### PR DESCRIPTION
**Pull request by yvan-sraka**
https://doc.rust-lang.org/cargo/reference/profiles.html#overrides

### CODE REVIEW

**Review by AureliaDolo — APPROVED** [review]

**Comment by yvan-sraka** [comment]
bors merge

**Comment by yvan-sraka** [comment]
bors merge

**Comment by AureliaDolo** [comment]
And another test that's failing on mc os :sparkles:

**Comment by yvan-sraka** [comment]
bors merge

**Pull request merged**
